### ISSUE TITLE
Duplicates in NFT.trades for bundled trades

### ISSUE THREAD

**Issue by bingowrt** [duneanalytics/spellbook#1064]
just check the trades amount of this new nft project
'\xa5Bb28eecC6134F89745E34ec6aB5d5Bcb16dAD7'
the daily trade amount doesn't match the amount in opensea.
Its probably because of joining different tables using hash, a lot of scenarios where one person buys multiple nft in one transaction.
the result will multiply. if a person does so.

my solution is getting transaction event from the eth.log, therefore get the hashes , then using the hashes to get the event that topic0 = opensea orders match
 though it's not perfect(if someone bought more than one kind of  nft in one transaction, it would be counted in our amount, but less probably), its better than the pervious one

my code
-- Bilibili NFT 
WITH transfer_hash_all
AS(
SELECT DISTINCT(tx_hash)
FROM ethereum."logs"
WHERE contract_address = '\xa5Bb28eecC6134F89745E34ec6aB5d5Bcb16dAD7'
AND topic1 = '\xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'
AND topic2 != '\x0000000000000000000000000000000000000000000000000000000000000000'
),
sell_hash 
AS (
SELECT *
FROM ethereum."logs" log
WHERE log.tx_hash IN (SELECT * FROM transfer_hash_all)
AND topic1 = '\xc4109843e0b7d514e4c093114b863f8e7d8d9a458c372cd51bfe526b588006c9'
)

SELECT date_trunc('day',block_time) as time ,COUNT(*) as trades_count FROM sell_hash
GROUP BY 1
ORDER BY 1 DESC

**Comment by soispoke** [comment]
Closing this issue as we're now looking to maintain nft.trades on our new Dune Engine v2
