### ISSUE TITLE
token_a_address and token_b_address should have clear definition   in dex.trades

### ISSUE THREAD

**Issue by CodingChangeTheWorld** [duneanalytics/spellbook#1072]
for example:
in uniswap v2,token_b_address means src_token,token_a_address  means to_token,
in paraswap,,token_a_address means src_token,token_b_address  means to_token,
there is no standard definition abount two addresses

**Comment by CodingChangeTheWorld** [comment]
so many people judge sell or buy by following code,the all data are really wrong
    CASE
        WHEN token_b_address = '\x6f80310ca7f2c654691d1383149fa1a57d8ab1f8' THEN 'Sell'
        ELSE 'Buy'
    END AS action,

**Comment by k06a** [comment]
That's definitely needs to be fixed! Let's make token_a = src_token for the swap initiator (taker).

**Comment by soispoke** [comment]
Thanks for your comments, let's fix this in dex.trades on Dune v2 :)
