### ISSUE TITLE
dex.liquidity version for Curve is wrong

### ISSUE THREAD

**Issue by bizzyvinci** [duneanalytics/spellbook#1216]
All the version in dex.liquidity for curve is `'1'` cause that's what was inserted in the [query](https://github.com/duneanalytics/abstractions/blob/9a7e4d9412bcb251a156f58f5e2a0cdb483df843/ethereum/dex/liquidity/insert_curve.sql)

A look at `distinct version` on tables `dex.trades` and `curvefi."view_pools"` would result in
1. Factory V1 Meta
2. Factory V1 Plain
3. Factory V2
4. Regular

I have 2 suggested solution
1. Use the same version as `dex.trades` and `curvefi.view_pools` by simply updating version in [liquidity query](https://github.com/duneanalytics/abstractions/blob/9a7e4d9412bcb251a156f58f5e2a0cdb483df843/ethereum/dex/liquidity/insert_curve.sql) starting from [`curve_pool_tokens`](https://github.com/duneanalytics/abstractions/blob/9a7e4d9412bcb251a156f58f5e2a0cdb483df843/ethereum/dex/liquidity/insert_curve.sql#L8-L18) downwards.
2. Take it a step further and edit [curvefi.view_pools](https://github.com/duneanalytics/abstractions/blob/7777cf26da41799117057543c3403adfac00fcd5/ethereum/curvefi/view_pools.sql) by updating `Regular` to either `Regular V1` or `Regular V2` so that there's clearer knowledge of V1 vs V2.

Challenge with step 2 is that it might affect older queries and Messari projects. But it's probably worth it knowing the difference between Regular V1 and Regular V2. Therefore I'm seeking approval or suggestion from @yulesa too.

**Comment by yulesa** [comment]
Curve's dex.trades was updated but Curve's dex.liquidity was not.
I have a liquidity update to make, but I was in the process of checking it out before getting dragged to other works.
I have a view you can check here: https://dune.com/queries/756375.
Transforming this into an insert curve liquidity would be a better solution?

**Comment by bizzyvinci** [comment]
Thanks @yulesa for the query. And what do you think about updating version in [curvefi.view_pools](https://github.com/duneanalytics/abstractions/blob/7777cf26da41799117057543c3403adfac00fcd5/ethereum/curvefi/view_pools.sql). The `Regular` pools contain both V1 and V2.

**Comment by yulesa** [comment]
no problem.

**Comment by bizzyvinci** [comment]
Would solve the issue this week. This [query](https://dune.com/queries/957508) also shows that almost all V2 pools have null liquidity.
