### ISSUE TITLE
nft.trades bug - incorrect nft_contract_address for seaport weth accepted offers

### ISSUE THREAD

**Issue by catherine-2** [duneanalytics/spellbook#1309]
Chatted with @sohwak via DM but wanted to open here as well so we can keep track of the discussion and hopefully figure out what is causing this bug!

WETH accepted offers are currently not pulling in the correct nft_contract_address in the nft.trades tables. As a result overall NFT volumes are correct, but any summary data on # or volume of transactions on a project level is incorrect post-Seaport launch.

Example tx_hash = 0x4a2b67b16f5f84ade5edbc5cdc5e11840089fe582200815eae0ea9002e768736
In nft.trades the currency_contract (weth contract address) = nft_contract_address. In this example the nft_contract_address should instead be 0xa7d8d9ef8D8Ce8992Df33D8b8CF4Aebabd5bD270.

So far we think the bug is coming from this abstraction: https://github.com/duneanalytics/abstractions/blob/master/ethereum/nft/trades/insert_seaport.sql

This section of the code breaks out "buy now" vs. "offer accepted" transactions:
          ,max(case when nft_transfer_count = 1 and item_type in ('2','3') then token_contract_address::text 
                    else token_contract_address::text 
               end)::bytea as nft_contract_address

The token contract address pulls in 
          ,concat('\x',substr(a.consideration2->>'token',3,40))::bytea as token_contract_address

from: 
        (select *
                     from seaport."Seaport_evt_OrderFulfilled" a
                         ,jsonb_array_elements(a.consideration) with ordinality as c (consideration2, consideration_idx)
                    where a.recipient = '\x0000000000000000000000000000000000000000'::bytea
                      and a.zone in ('\xf397619df7bfd4d1657ea9bdd9df7ff888731a11'::bytea
                                   ,'\x9b814233894cd227f561b78cc65891aa55c62ad2'::bytea
                                   ,'\x004c00500000ad104d7dbd00e3ae0a5c00560c00'::bytea
                                   )
                   ) a

**Comment by dot2dotseurat** [comment]
Thank you @catherine-2. We will get this fixed.

**Comment by catherine-2** [comment]
Thank you @dot2dotseurat !

**Comment by dot2dotseurat** [comment]
@sohwak I looked into this and it looks like nft_contract_id needs to be extracted from the consideration where item type is 2. 

I have a query here that I'm using as a unit test to confirm. Can you confirm that this will resolve the issue?
https://dune.com/queries/1103867

On V2, we would add something like the query above as a unit test in the repo but we don't have a way to do that on V1.

**Comment by catherine-2** [comment]
@dot2dotseurat @sohwak  Thank you! This unit test looks correct to me. 

I wanted to check in and see when you both think this will be able to be fixed? It is causing some problems on dashboards given the high % of WETH offers accepted lately so would be helpful to have an ETA to share with others. Thank you!

**Comment by dot2dotseurat** [comment]
Let me see if there is another channel to ask @sohwak about this. I'd like him to validate the fix I proposed in the unit test above. I am not familiar enough with the code to make the change myself.

**Comment by catherine-2** [comment]
Thank you @dot2dotseurat !

**Comment by sohwak** [comment]
Hi @catherine-2, sorry I was late to reply this issue. 
I found the reason causes this, and now it is fixed with below pull request:
https://github.com/duneanalytics/abstractions/pull/1340
FYI, all rows are NFT-based so you could use nft_contract_address/nft_token_id for each.
Thanks.

**Comment by catherine-2** [comment]
Thank you so much @sohwak ! Do you know when the data will be updated in Dune queries? From the pr comments it looked like jeff-dude said the history was reloaded but when I just ran a test query (copied below) the currency_contract still = nft_contract_address column.

select * from nft.trades_v2_beta 
where tx_hash = '\x4a2b67b16f5f84ade5edbc5cdc5e11840089fe582200815eae0ea9002e768736'

**Comment by sohwak** [comment]
it is applied to `nft.trades` currently.
```
select * from nft.trades
where tx_hash = '\x4a2b67b16f5f84ade5edbc5cdc5e11840089fe582200815eae0ea9002e768736'
```

for `nft.trades_v2_beta`, it need more time to apply I think.

**Comment by sohwak** [comment]
Hi, @catherine-2 
This issue looks well resolved. I found `nft.trades_v2_beta` has the right result as well. To close the resolved issue helps Dune team to concentrate on other issues more, in my opinion :) Thanks.
