### ISSUE TITLE
polygon.blocks miner field incorrect

### ISSUE THREAD

**Issue by jacubcub** [duneanalytics/spellbook#1386]
The "miner" field (validator's address) in the polygon blocks table is 0x00...000 for every block starting from 2021-09-21. Here is a query that shows the issue. https://dune.com/queries/1174835

Expected behavior: "validated by" address should populate the miner field. Sample block with validator address on polygonscan https://polygonscan.com/block/31965482

**Comment by jeff-dude** [comment]
hi @jacubcub -- apologies for the (long) delay. we're going through the issues page to clean it up & repurpose for more useful collaboration.

i've raised this internally to our team which handles the base tables. depending on response, i can follow up here to resolve/close.
