### ISSUE TITLE
Incorrect NFT balances on v2

### ISSUE THREAD

**Issue by 0xRobin** [duneanalytics/spellbook#1524]
# Issue
`balances_ethereum.erc721_hour` and presumable other NFT balance queries don't produce expected results.

We expect for each timestamp only one `wallet_address` to be reported for each (`token_address`, `tokenId`).
This is not the case.

Example query:
https://dune.com/queries/1246260
```sql
select * from balances_ethereum.erc721_hour 
where blockchain = 'ethereum' 
and token_address='0x0427743df720801825a5c82e0582b1e915e0f750' and tokenId = 94 
and hour = '2022-09-04 00:00'
```
results in multiple reported owners.
![image](https://user-images.githubusercontent.com/83790096/188833948-48ae11f7-9c75-402c-8ea5-2d6b5e390d33.png)
The correct owner should be: `0xdb3a6a88f39a3a0bd0e9e86eaa4df396768bd98c`
https://etherscan.io/nft/0x0427743df720801825a5c82e0582b1e915e0f750/94

## Test correction
This issue is probably live for ~3months and was not detected because of faulty test implementation.
`wallet_address` should **not** be included in the group clauses (and select) here:
https://github.com/duneanalytics/spellbook/blob/b61761e5d381146875100a0ac939438044e9fe0d/tests/balances/ethereum/balances_ethereum_erc721_day_assert_nomultipleholders.sql#L11
https://github.com/duneanalytics/spellbook/blob/b61761e5d381146875100a0ac939438044e9fe0d/tests/balances/ethereum/balances_ethereum_erc721_hour_assert_nomultipleholders.sql#L11

**Comment by soispoke** [comment]
Thanks @0xRobin, will fix the test, investigate this and get back to you

**Comment by 0xRobin** [comment]
Fixed
