### ISSUE TITLE
seaport.transfers sometimes under reporting price and fees

### ISSUE THREAD

**Issue by 0xRobin** [duneanalytics/spellbook#1573]
### Issue

In the current query implementation of [seaport.transfers](https://github.com/duneanalytics/spellbook/blob/fe0b71e4b5acfc3f877ede39ab1831fd2917acb2/models/seaport/ethereum/seaport_ethereum_transfers.sql)
we often use the following sub_idx structure when parsing the `consideration` data:
idx 0 -> payment
idx 1 -> protocol fee
idx 2 -> royalty fee
example:
https://github.com/duneanalytics/spellbook/blob/fe0b71e4b5acfc3f877ede39ab1831fd2917acb2/models/seaport/ethereum/seaport_ethereum_transfers.sql#L257-L259

There can however be more then 1 royalty payment (with idx > 2).
example tx: https://etherscan.io/tx/0xb7dcca50ffef23121f0f326aac946c886c958b7e6eee2747393015053e8f269a
event logs: https://dashboard.tenderly.co/tx/mainnet/0xb7dcca50ffef23121f0f326aac946c886c958b7e6eee2747393015053e8f269a/logs

Because we're only accounting for idx <= 2, we end up under reporting the fees payed.

example:
This 0.5 ETH buy is underreported as 0.475 ETH
https://dune.com/queries/1281269

Edit: The same faulty logic might have been applied to the `offer` array..

**Comment by 0xRobin** [comment]
### Issue impact
Total impacted transfers: 95900
https://dune.com/queries/1281292?

**Comment by 0xRobin** [comment]
@soispoke while the bigger seaport issue with double counting fees was resolved.
This issue is still present.

**Comment by soispoke** [comment]
@0xRobin  👍 reopening then, until we get to it (tagging @sohwak again if you have time to take a look)

**Comment by 0xRobin** [comment]
closing cause issue is resolved in seaport.trades
