### ISSUE TITLE
Empty fields in CoW Trades

### ISSUE THREAD

**Issue by bh2smith** [duneanalytics/spellbook#1627]
There seems to be an issue (originating from #1591) populating the `evt_index` and `project_contract_address` or this table:

There are 384705 records with empty value here...

 See Query: https://dune.com/queries/1303727

_Originally posted by @bh2smith in https://github.com/duneanalytics/spellbook/issues/1591#issuecomment-1256877207_

**Comment by soispoke** [comment]
Issue fixed in merge PR #1591
