### ISSUE TITLE
V2: Multiple Duplicate Records in ens_resolver_addresses

### ISSUE THREAD

**Issue by bh2smith** [duneanalytics/spellbook#1651]
[This query](https://dune.com/queries/1324487?d=1&category=abstraction&namespace=ens&table=view_registrations&blockchains=ethereum) demonstrates 512 duplicates for a single ens name:

https://github.com/duneanalytics/spellbook/blob/main/models/ens/ens_resolver_addresses.sql

I haven't had chance to check the reason for this.

**Comment by 0xRobin** [comment]
> Seems to be related to #1569
Indeed related, I'm gonna get started on an ENS spell rework tomorrow that should fix it. 
I'll probably prioritize the reverse ens records first.

**Comment by bh2smith** [comment]
@0xRobin - I see the relented branch was merged. Does this close the issue?

**Comment by 0xRobin** [comment]
@bh2smith yeah, reverse records should be fine now and shouldn't contain duplicates.
Still working on the resolve records (ens -> address)

**Comment by bh2smith** [comment]
I think there still may be somethign subtly off about this table.... unless maybe I misunderstood the meaning. but this pair

`(bahman.eth, 0x428824314a823c89241EBCdfCccA8932C4573c4a)` doesn't show up in the table at all if one searches for either address or name.

Does the reverse lookup have somethign to do with wallets that registered the domain?

**Comment by jeff-dude** [comment]
closing as this spell no longer exists (or was rebuilt / renamed)
