### ISSUE TITLE
Token Prices Not in Table (wstETH & rETH)

### ISSUE THREAD

**Issue by bh2smith** [duneanalytics/spellbook#1785]
https://github.com/duneanalytics/spellbook/blob/df795b398746c0fb132db32a8f63e8414301a85c/models/prices/prices_tokens.sql#L590-L591

Among these two tokens both rETH and wstETH are not appearing in the table at all:

1. [rETH](https://coinpaprika.com/coin/reth-rocket-pool-eth/) appears to be "inactive" on coin paprika (which makes sense).
2. [wstETH](https://coinpaprika.com/coin/wsteth-wrapped-liquid-staked-ether-20/) is NOT inactive

cf: this query

```sql
select count(*) from prices.usd where
contract_address in (
    '0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0',
    '0xae78736cd615f374d3085123a210448e74fc6393'
)
```

**Comment by jeff-dude** [comment]
this appears resolved
```
select
  contract_address,
  count(*)
from
  prices.usd
where
  contract_address in (
    0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0,
    0xae78736cd615f374d3085123a210448e74fc6393
  )
group by
  contract_address
```
