### ISSUE TITLE
Contract Addresses Not Unique in ethereum.contracts

### ISSUE THREAD

**Issue by bh2smith** [duneanalytics/spellbook#1825]
I am trying to figure out why there are multiple contracts (with different names) at the same address. 

[This query](https://dune.com/queries/1434824?d=1) shows that there are over 2000 occurrences of contracts appearing more than once by address. My best guess at what this could be is upgradable contracts, but it still seems very strange that there are duplicates... can someone help out here? It also appears the same thing is happening in [V1 as well](https://dune.com/queries/1434837?d=4).

**Comment by UmerHA** [comment]
We spoke about this issue in the office hours. According to boxer, this seems to be a bug

**Comment by bh2smith** [comment]
Is there any plan to fix this? I would offer to help but I don't think it can be done from within this project.

**Comment by UmerHA** [comment]
If I understood correctly they're going to fix it. But I don't know the timeline/priority. I think your best shot is to join the office hours & ask the Dune team directly

**Comment by bh2smith** [comment]
I should really start doing that! Great suggestion
