### ISSUE TITLE
incorrect nft.trades data (number_of_items & amounts) for some Seaport ERC-1155 trades

### ISSUE THREAD

**Issue by denz-e** [duneanalytics/spellbook#1836]
I've identified some scenarios where the nft.trades table is incorrect for ERC-1155's in relation to seaport transactions: https://github.com/duneanalytics/spellbook/blob/main/models/seaport/ethereum/seaport_ethereum_transfers.sql

As an example, I'm looking at sales of this NFT: 0x33cfae13a9486c29cd3b11391cc7eca53822e8c7 using this query: https://dune.com/queries/1353417

<img width="1386" alt="image" src="https://user-images.githubusercontent.com/105643570/197668201-e14770c7-c472-478e-ac6a-9fa6ca31185b.png">

From spot checking ~20 transactions, there are two issues:

**Issue 1) incorrect number_of_items for fulfillAdvancedOrder (p3_ in seaport_ethereum_transfers):** showing as 1 when there are multiple NFTs being purchased

- example: https://etherscan.io/tx/0x8f799a73b30516ef950a6d2f147e811966d278608e81aa300066d28d8d64c34d/

**Issue 2) incorrect amount_original & amount_usd for portions of transactions for fulfillAvailableAdvancedOrders (p2_ in seaport_ethereum_transfers):**

- example 1: https://etherscan.io/tx/0xf63c08c958ca4a44b74bec6dcbb2f5ecb2d9969335e23e78c6ca92c654845606/
- example 2: https://etherscan.io/tx/0x6e449e92cb2ecedd5180c3399b0eafb4c81e3a6979c7daf0cca1be9361c1d227/
- example 3: https://etherscan.io/tx/0x4ca37df90b8d85966f9d6542e38499508119e9500cd686595275a6aaa3791200/

I haven't seen any issues with fulfillBasicOrder (p1_ in seaport_ethereum_transfers)

**Comment by denz-e** [comment]
**RE: Issue 1**

I think the wrong value is being used for _number_of_items_ in the p3_seaport_transfers CTE. It's getting the nft_transfer_count but I think it should be getting the nft_item_count, as per p1_seaport_transfers

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/105643570/197671659-292be33a-18bc-4e1f-a7b9-eaaae3ed3b7d.png">

Not sure if there's more to it then that but it would fix all the transactions that I've seen to be incorrect

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/105643570/197673617-b2206255-9a82-49d3-b645-60661f29f46e.png">

**Comment by denz-e** [comment]
**RE: Issue 2**

From the Seaport smart contract: _"Advanced orders include a numerator (i.e. a fraction to attempt to fill) and a denominator (the total size of the order) in addition to the signature and other order parameters"_

The current calculation of prices isn't accounting for the numerator and denominator.

<img width="1690" alt="image" src="https://user-images.githubusercontent.com/105643570/197691256-4db0d8a2-8883-4a2e-a291-095b2e542797.png">

I believe the fix may involve:

- adding new lines to get the numerator and denominator in p2_call
- multiplying price, fee, and royalty amounts by (numerator/denominator) in p2_transfer_level

**Comment by sohwak** [comment]
Hi @denz-e, Thank you for the heads-up. I am preparing the patch for this. I will submit it in the near days.

**Comment by denz-e** [comment]
Amazing, thanks @sohwak - excited for the patch!

**Comment by 0xRobin** [comment]
@denz-e I just rechecked manually and this looks like it is resolved. Thanks for reporting!
