### ISSUE TITLE
duplicate record

### ISSUE THREAD

**Issue by liangmengmeng1993** [duneanalytics/spellbook#1882]
it looks like a duplicate record 
![image](https://user-images.githubusercontent.com/26103353/199693990-3677e483-fc1e-48b9-83e2-eb91d1508768.png)
using v2 

sql is :
select * from nft.trades where tx_hash = '0xe0d483981e8ba27e891a5183972ffd62c3eab406989849014e4cfc90f859b2f3'

**Comment by Hosuke** [comment]
Hi @liangmengmeng1993 , I am currently review [this query](https://dune.com/queries/1538005) result.
<img width="659" alt="image" src="https://user-images.githubusercontent.com/6568873/200221051-352b39b4-31ce-4cc5-adf8-44a3c4501f80.png">
As you can see here, there is a small difference in their `unique_trade_id`.
This part is corresponding with their `erc.evt_index`.

To understand better about this case, we can [look this trade in etherscan.io](https://etherscan.io/tx/0xe0d483981e8ba27e891a5183972ffd62c3eab406989849014e4cfc90f859b2f3#eventlog).

**Comment by Hosuke** [comment]
<img width="937" alt="image" src="https://user-images.githubusercontent.com/6568873/200221582-5b192676-d9e9-4e40-8e8e-a108368e3a13.png">
In event#189, this token with ID 136 is being transferred from 0x0a525565977c64967821e15905FA476eED7f70cF to 0x83C8F28c26bF6aaca652Df1DbBE0e1b56F8baBa2.
<img width="803" alt="image" src="https://user-images.githubusercontent.com/6568873/200222917-6bb343c4-a11d-4b62-98ec-eaf25b859f87.png">
And in event#192, this token with ID 136 is being transferred from 0x83C8F28c26bF6aaca652Df1DbBE0e1b56F8baBa2 to 0x1544D2de126e3A4b194Cfad2a5C6966b3460ebE3.

---
These two events actually show in the tx overview:
<img width="856" alt="image" src="https://user-images.githubusercontent.com/6568873/200223137-8b0001d6-f719-4a13-bb8f-e8c2fdc2a480.png">
So 0x83C8F28c26bF6aaca652Df1DbBE0e1b56F8baBa2 is actually [GemSwap 2 contract adddress](https://etherscan.io/address/0x83c8f28c26bf6aaca652df1dbbe0e1b56f8baba2#code), which is indicated in the aggregator_address in the query above.
<img width="726" alt="image" src="https://user-images.githubusercontent.com/6568873/200223657-9a3e1c28-885e-4822-98c3-c10461f6b09d.png">

**Comment by Hosuke** [comment]
> ![image](https://user-images.githubusercontent.com/26103353/200245240-510ea0f3-0943-410d-9272-164770b1d505.png) as I understand ,in event#189 ,the from should be 0x0a525565977c64967821e15905FA476eED7f70cF and to should be 0x83C8F28c26bF6aaca652Df1DbBE0e1b56F8baBa2.
> 
> and in event#192, the from should be 0x83C8F28c26bF6aaca652Df1DbBE0e1b56F8baBa2 and to should be 0x1544D2de126e3A4b194Cfad2a5C6966b3460ebE3.
> 
> Can I understand it this way？

`tx_from` and `tx_to` are addresses linked to this specific transaction (join on `tx_hash` from `ethereum.transactions`), as you can see the wallet was interacting with the contract. You can check the column `seller` and `buyer` for the transfer of this token.

(Also cc @soispoke to confirm that my interpretation is correct)

**Comment by soispoke** [comment]
@Hosuke Yes that's the right interpretation :)

**Comment by liangmengmeng1993** [comment]
ok,thank you very much @Hosuke @soispoke
