### ISSUE TITLE
1inch Trades Missing since new Router

### ISSUE THREAD

**Issue by bh2smith** [duneanalytics/spellbook#2197]
[1inch's latest trade](https://dune.com/queries/1694390) in dex.trades v1 is November 30th.

My best guess is that this PR - #1977 - which changes the cron-settings and back fill methods is to blame.

**Comment by bh2smith** [comment]
Hey @fatayri - since you made this PR, would mind taking a look at this?

**Comment by fatayri** [comment]
Hey @bh2smith! We're on it, there is a bug in my latest PR, fixing it.

**Comment by fleupold** [comment]
https://github.com/duneanalytics/spellbook/pull/2117 is the PR containing the fix
