### ISSUE TITLE
some data missing in nft.mints table

### ISSUE THREAD

**Issue by orangepeach** [duneanalytics/spellbook#2285]
following data in nft.mints is missing or wrong
```
collection
amount_usd
amount_original
amount_raw
currency_symbol
currency_contract
```

**Comment by 0xRobin** [comment]
do you have any specific examples which are wrong?

**Comment by tad3j** [comment]
@0xRobin , for example they are missing for this contract: `0xf9e39ce3463b8def5748ff9b8f7825af8f1b1617`

I can see mints with query bellow but none is returned by the spell:
```
SELECT
  *
FROM
  nft.transfers
WHERE
  contract_address = 0xf9e39ce3463b8def5748ff9b8f7825af8f1b1617
  AND "from" = 0x0000000000000000000000000000000000000000
```

**Comment by tad3j** [comment]
`collection` column is blank/missing for this Ethereum contract: `0xf9e39ce3463b8def5748ff9b8f7825af8f1b1617`
Here is a query with missing data:
```sql
SELECT
  *
FROM
  nft.mints
WHERE
  nft_contract_address = 0xf9e39ce3463b8def5748ff9b8f7825af8f1b1617
```

**Comment by jeff-dude** [comment]
> `collection` column is blank/missing for this Ethereum contract: `0xf9e39ce3463b8def5748ff9b8f7825af8f1b1617` Here is a query with all rows missing collection name and some are also missing `amount_usd`:
> 
> ```sql
> SELECT
>   *
> FROM
>   nft.mints
> WHERE
>   nft_contract_address = 0xf9e39ce3463b8def5748ff9b8f7825af8f1b1617
> ```

this query returns 999 rows now, as expected from the closed linked issue. this should be good to close.
