### ISSUE TITLE
DOCS: Spellbook Overview mentions Sources section of github repo - doesn't exist (any more)

### ISSUE THREAD

**Issue by etc-chmod** [duneanalytics/spellbook#2539]
Wanted to let you know that in the docs of the dune spellbook, section overview <https://dune.com/spellbook#!/overview> there is a mention of a source section which I searched for but could not find. Maybe it has been moved or deleted?

Kind regards
etc

**Comment by Hosuke** [comment]
Hi @etc-chmod, the source section is here: https://dune.com/spellbook#!/source/source.spellbook.aave_ethereum.AaveGovernanceV2_evt_ProposalCanceled
Please have a look.

<img width="380" alt="image" src="https://user-images.githubusercontent.com/6568873/229566944-6bd07f14-99c5-48dc-bdb4-02afe6b6940c.png">

**Comment by etc-chmod** [comment]
Thank you, must have been blind or something.
