### ISSUE TITLE
Bug: Element NFT fees are hardcoded to 0%

### ISSUE THREAD

**Issue by 0xRobin** [duneanalytics/spellbook#2750]
### Description
Element NFT marketplace fees are all 0% on Dune but they do/did respect royalties when they are set on their site.

### Current behavior
All the fee columns are hardcoded to 0
https://github.com/duneanalytics/spellbook/blob/8f1bf80bc6f3627296959c109720d4d429e61b4b/models/element/ethereum/element_ethereum_events.sql#L147-L156

### Expected behavior
We should report the correct royalty amount. 
example with royalty:https://etherscan.io/tx/0xa33100a2702e900d369e3a7293d00ffdeb5e8269a604e0eb91b131a43f0f2ce3
![image](https://user-images.githubusercontent.com/83790096/220392573-b2fb960a-b2d9-4531-bfba-80f4192d6424.png)

### Concerned model(s)
```
element_ethereum.events
element_bnb.events
element_avalanche.events
```

### Impacted model(s)
```
nft.events
nft.trades
nft.fees
```
~97k Rows affected

### Possible solution
There are no events emitted on royalty payments, but there is fee information embedded in the contract calls.
Pulling this information into the model could be a solution.

**Comment by jeff-dude** [comment]
leaving this open based on desc in linked PR.

are there any actions to take here?

**Comment by 0xRobin** [comment]
fees are still hard coded to zero.
Let's indeed leave open until someone can look into it.

**Comment by Nancy9ice** [comment]
Hello, 

I'm currently working on this issue. I can see the referenced sql file that contains the columns to be edited. Please is this the latest branch to start work on? If no, what is the latest branch?

**Comment by 0xRobin** [comment]
you can start from `main`

**Comment by Nancy9ice** [comment]
Ok. Listed below are the three sql files that I'll be working on.
spellbook/models/element/ethereum/element_ethereum_events.sql
spellbook/models/element/avalanche_c/element_avalanche_c_events.sql
spellbook/models/element/bnb/element_bnb_events.sql

Unfortunately, the 'element' folder don't exist in the main branch. Would you want me to move the 'element' folder bearing in mind that there are other files not related to this issue in the 'element' folder? Or would you want me to move only the three sql files that concerns this issue?

**Comment by Nancy9ice** [comment]
Okay. Thank you for this clarification. I have edited this stated macros file, tested it, and created a pull request. Please review it as soon as you can. 

Here's the direct link:
https://github.com/duneanalytics/spellbook/pull/5523
