### ISSUE TITLE
[CoW] Incorrect Trades Schema!

### ISSUE THREAD

**Issue by bh2smith** [duneanalytics/spellbook#2794]
We have been fighting with this for months and still can't seem to get it right.

The schema shown for the "outer" (combined trades table) is the same as the one for the inner (even though those columns do not exist).

This screenshot shows that the `cow_protocol.trades` schema is displaying the `cow_protocol_ethereum.trades` schema in the interface.

cc @gentrexha (do we remember if we landed on a renaming approach to eliminate this issue?).

Someone please make it right!

<img width="1017" alt="Screenshot 2023-02-23 at 11 47 54" src="https://user-images.githubusercontent.com/11778116/220885960-416a3a43-7a8a-4c41-b6d4-4de16c6f50c6.png">

**Comment by gentrexha** [comment]
> cc @gentrexha (do we remember if we landed on a renaming approach to eliminate this issue?).

Unfortunately, I can't remember.

**Comment by dot2dotseurat** [comment]
This is the fault of our data explorer being unclear. That schema is the cow_protocol_ethereum table. See how it only have the ethereum logo?
<img width="197" alt="Screen Shot 2023-02-27 at 3 53 57 PM" src="https://user-images.githubusercontent.com/9472574/221683350-7f44773b-49eb-4038-8cb3-03e8d9724011.png">

The schema was both logos is the schema for `cow_protocol.trades`
<img width="439" alt="Screen Shot 2023-02-27 at 3 54 46 PM" src="https://user-images.githubusercontent.com/9472574/221683406-d34a9448-808c-45fc-8497-c9b112154728.png">

I'll forward this to the designer who is working on the redesign. I've fallen for the same trap so I agree it's confusing.

**Comment by bh2smith** [comment]
Right - of course thanks!
