### ISSUE TITLE
[BUG] error identifying creator royalties in seaport

### ISSUE THREAD

**Issue by mikeshultz** [duneanalytics/spellbook#3013]
### Description

It seems the Seaport spellbook is not identifying creator royalties properly.  For this example, we can use [`0x926a8aa3e9e7dec6a8855ca7a772a41b12a7ada6f38cd2f109e7146d05e2303b`](https://etherscan.io/tx/0x926a8aa3e9e7dec6a8855ca7a772a41b12a7ada6f38cd2f109e7146d05e2303b) or [`0x79fbb2da85b3c7c38704306c3fb95bcf4d84c926a294f323987ae2ccf74467c5`](https://etherscan.io/tx/0x79fbb2da85b3c7c38704306c3fb95bcf4d84c926a294f323987ae2ccf74467c5).  

### Current behavior

Looks like it's currently using the index of the consideration in the vent to identify which is a royalty payment.  This *only* accurate for orders generated by OpenSea that include their platform fee.

```psql
case when offer_first_item_type = 'erc20' and sub_type = 'consideration' and eth_erc_idx > 1 then true
    when offer_first_item_type in ('erc721','erc1155') and sub_type = 'consideration' and eth_erc_idx > 2 then true
    else false
end is_creator_fee
```

However, it's not correct as the example orders are sending Royalties to `0x2dE038A402119bCbd49A4412c35f27670801eD4e` which has an `eth_erc_idx = 1` and no OpenSea platform fee.

### Expected behavior

I would expect this to correctly identify this consideration as a creator royalty.

### Impacted model(s)

Lots of things depend on it, but the primary issue seems to be at:

```
seaport_ethereum.base_pairs
```

### Possible solution

I'm not immediately sure what the ideal solution is here.  Could maybe look to see if the recipient of the consideration is the royalty address, but that's not static and I'm not sure if it's in the dataset.  If I think of anything I'll reply here.

CC @sohwak

**Comment by sohwak** [comment]
Hi @mikeshultz, thank you for this heads up. I were aware of the issue. It's a bit late, but I am fixing it in here:
https://github.com/duneanalytics/spellbook/pull/3034

**Comment by jeff-dude** [comment]
since linked PR is merged, closing this
