### ISSUE TITLE
[BUG] tokens_ethereum.erc20 addresses are varchar

### ISSUE THREAD

**Issue by MSilb7** [duneanalytics/spellbook#3022]
### Description

This returns varchar. So joins using this table are difficult since it requires casting.
```
SELECT
typeof(contract_address)
FROM tokens_ethereum.erc20
limit 1
```

### Current behavior

`contract_address` is varchar

### Expected behavior

`contract_address` is varbinary

### Impacted model(s)

```
tokens_ethereum.erc20
```

### Possible solution

Modify the tokens_ethereum.erc20 spell. May require manual lower case forcing so that it works in both Spark and DuneSQL

**Comment by jeff-dude** [comment]
we seem to be a bit in limbo here. first off, this would affect all `tokens_*` spells, not only ethereum. if we edit the spell to remove single quotes, the dbt orchestration still runs on spark at this time, so it'll fail. these are all materialized as tables, not views. until we switch ETL engine over to trino, i'm not sure we can change this in spellbook.

@belen-pruvost how do we handle this for other spells (if we do)? would we need manual overrides for it in dunesql for now, to make these addresses varbinary?

**Comment by belen-pruvost** [comment]
Hey @jeff-dude - limbo indeed 😅 since varbinary is not a supported type on Spark, it needs to be introduced as a type on the overrides file (which is not open source, we can tweak it internally). 

For each view and column we want to have varbinaries in, we would need to:
1) Make sure that these columns are always convertible to varbinary - using the `_unsafe_0x_or_base58_to_varbinary` function (like [this](https://dune.com/queries/2259081), making sure there are no values that would make the function fail - which is the case if it has values that can't be converted to base58)
2) Update the overrides file

I can help with the overrides file if you folks help with gathering the list of views, columns and making sure they are actually convertible.

**Comment by jeff-dude** [comment]
> Hey @jeff-dude - limbo indeed 😅 since varbinary is not a supported type on Spark, it needs to be introduced as a type on the overrides file (which is not open source, we can tweak it internally).
> 
> For each view and column we want to have varbinaries in, we would need to:
> 
> 1. Make sure that these columns are always convertible to varbinary - using the `_unsafe_0x_or_base58_to_varbinary` function (like [this](https://dune.com/queries/2259081), making sure there are no values that would make the function fail - which is the case if it has values that can't be converted to base58)
> 2. Update the overrides file
> 
> I can help with the overrides file if you folks help with gathering the list of views, columns and making sure they are actually convertible.

what if the spells are tables and not views? does this still work?

**Comment by belen-pruvost** [comment]
> what if the spells are tables and not views? does this still work?
Yes, same idea applies

**Comment by jeff-dude** [comment]
> > what if the spells are tables and not views? does this still work?
> > Yes, same idea applies

okay, if i run: `dbt ls --resource-type model --select +tokens_erc20` to see spells within it's hierarchy, we have the following which would need overridden for the datatype asked in original description:
> spellbook.ovm.optimism.ovm_optimism_l2_token_factory
> spellbook.tokens.arbitrum.tokens_arbitrum_erc20
> spellbook.tokens.avalanche_c.tokens_avalanche_c_erc20
> spellbook.tokens.bnb.tokens_bnb_bep20
> spellbook.tokens.tokens_erc20
> spellbook.tokens.ethereum.tokens_ethereum_erc20
> spellbook.tokens.fantom.tokens_fantom_erc20
> spellbook.tokens.gnosis.tokens_gnosis_erc20
> spellbook.tokens.optimism.tokens_optimism_erc20
> spellbook.tokens.optimism.tokens_optimism_erc20_bridged_mapping
> spellbook.tokens.polygon.tokens_polygon_erc20

we can work together on that repo to make this happen?
how do we go about the change without knowing full impact to end users? while we solve this problem, do we create more?

**Comment by belen-pruvost** [comment]
> we can work together on that repo to make this happen? 
Sure! Do you want to confirm that addresses are correct with a query similar to what I shared, and I push the override update?

> how do we go about the change without knowing full impact to end users? 
by changing the type we could break existing queries if they are joining / concatenating / comparing the address file with a varchar value, i think it's a risk we can't avoid or mitigate

**Comment by jeff-dude** [comment]
> > we can work together on that repo to make this happen?
> 
> Sure! Do you want to confirm that addresses are correct with a query similar to what I shared, and I push the override update?
> 
> > how do we go about the change without knowing full impact to end users?
> 
> by changing the type we could break existing queries if they are joining / concatenating / comparing the address file with a varchar value, i think it's a risk we can't avoid or mitigate

this is related to items raised internally in the query team channel. i think we should wait until we have a bit more clarity on how to proceed with minimal impact
cc @augustog

**Comment by belen-pruvost** [comment]
Makes sense - let's discuss this this week @jeff-dude 🙌

**Comment by jeff-dude** [comment]
this is no longer an issue, running spellbook on dunesql engine
