### ISSUE TITLE
[BUG] Perpetual Trades DuneSQL model not pickup up upstream 'frontend' colums

### ISSUE THREAD

**Issue by MSilb7** [duneanalytics/spellbook#3051]
### Description

Another weird one:
Since merge of https://github.com/duneanalytics/spellbook/pull/3023 (related to https://github.com/duneanalytics/spellbook/issues/3019) querying perpetual.trades in DuneSQL now throws an error

```
Error: Line 1:15: Failed analyzing stored view 'delta_prod.perpetual.trades': line 96:4: Column 'frontend' cannot be resolved at line 1, position 15.
```

But in SparkSQL, this succeeds.

Example query:
`SELECT * FROM perpetual.trades limit 1000`

### Current behavior

Error in DuneSQL

### Expected behavior

Query works like SparkSQL

### Impacted model(s)

```
perpetual.trades
```

**Comment by jeff-dude** [comment]
if this is still an issue, i'll look to fix for ya. it has to do with our data type override file that lives in a private repo. this process will soon change to be more efficient

**Comment by MSilb7** [comment]
I think this is resolved now. I'll mark as closed
