### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xalexec** [duneanalytics/spellbook#3059]
### Description
*** 1

select ROUND(100 * 0.1 / 100, 2)
UNION
select ROUND(100 * 0.01 / 100, 2)
UNION
select ROUND(100 * 212 / 391, 2)

in dune v2 result is 
54
0.01
0.1
in spark v2 result is
54.22
0.1
0.01

*** 2
select *
from ethereum.transactions
where value>0 LIMIT 5

select *
from ethereum.traces
where value>0 LIMIT 5

ethereum.transactions no problem
ethereum.traces Cannot apply operator: UINT256 < integer

### Impacted model(s)

```
namespace.model
```

**Comment by xalexec** [comment]
`value>cast(0 as uint256)`
ethereum.traces must use like this
but 
ethereum.transactions use this throw error

in docment the two table value is same uint256

**Comment by jeff-dude** [comment]
@aalan3 can you help clarify on these base table issues? this was last month, so potentially resolved, but tagging in case
