### ISSUE TITLE
[BUG] erc20.transfers varbinary/varchar datatype issues in DuneSQL

### ISSUE THREAD

**Issue by MSilb7** [duneanalytics/spellbook#3108]
### Description

erc20.transfers (https://github.com/duneanalytics/spellbook/blob/main/models/transfers/optimism/erc20/transfers_optimism_erc20.sql) returns a varchar/varbinary union issue in DuneSQL

### Current behavior

`Failed analyzing stored view 'delta_prod.transfers_optimism.erc20': line 51:1: column 3 in UNION query has incompatible types: varbinary, varchar(4) at line 1, position 15`

### Expected behavior

Varbinary datatype

### Impacted model(s)

```
erc20.tokens
```
As well as chain-specific tables generated in @tschubotz 's PR: https://github.com/duneanalytics/spellbook/pull/2949

### Possible solution

Cast all as varchar? Cast all as varbinary?

**Comment by 0xRobin** [comment]
@belen-pruvost @jmsgu
can you take a look at the dunesql type overrides here?

this fails:
`select * from transfers_optimism.erc20 limit 1` 
Some further context:

```
-- describe transfers_optimism.erc20
wallet_address | varchar
token_address | varchar
```
parent models:
```
-- describe erc20_optimism.evt_transfer 
from | varbinary 
to | varbinary
```
```
--  desribe weth_optimism.weth9_evt_deposit
dst | varbinary
```
```
--  describe weth_optimism.weth9_evt_withdrawal
src | varbinary
```

I'm thus not sure where the varchar in the union comes from. :thinking:

**Comment by tschubotz** [comment]
Hey, 
Just adding context, as this error was noticed before for related views. @jeff-dude suggested to rather rewrite the affected views instead of digging for the underlying cause: https://github.com/duneanalytics/spellbook/pull/2953#issuecomment-1485843744

So far I only got to make the suggested changes for FTM here: https://github.com/duneanalytics/spellbook/pull/3060

**Comment by belen-pruvost** [comment]
Hey folks, thank you for raising this. Indeed, a spell override like [this](https://dune.com/queries/2326782) is missing. I will open a PR with the fix.

**Comment by jeff-dude** [comment]
i'll revisit this one to make sure we have it cleaned up
