### ISSUE TITLE
feat: OpenSea/seaport polygon data

### ISSUE THREAD

**Issue by mikeshultz** [duneanalytics/spellbook#3140]
We've been using `nft_fees` for some things and noticed it seems to be missing Seaport polygon data.  For Ethereum, the dependency path is `opensea_fees->opensea_ethereum_fees->opensea_ethereum_events->opensea_v4_ethereum_events->opensea_v4_ethereum_trades->seaport_ethereum_trades`.  This does not seem to exist for Polygon, though the base `seaport_polygon_trades` does.

I'd like to request Polygon support to be added.  It seems much of this is probably copy & paste from ethereum to polygon but I don't have a great understanding on spellbooks yet and duplicating code might not be the best approach.  Let me know what you think and let me know how I can help.

cc @soispoke @sohwak

**Comment by 0xRobin** [comment]
hey @mikeshultz, thanks for reporting some of the discrepancies in the data.
We're working on a bigger restructuring of the nft sector spells that should resolve that.

In the meantime I would advise to use `nft_events` as a replacement, as it will contain all the columns and data that's in `nft_fees`

**Comment by jeff-dude** [comment]
closing due to nft spells redesign
