### ISSUE TITLE
Where did the DAO Names/Labels Come from?

### ISSUE THREAD

**Issue by bh2smith** [duneanalytics/spellbook#3196]
This file has been renamed a few times so its difficult to tell where they originated, but I think it would be useful to add some comments on where this "hard coded" information came from. 

https://github.com/duneanalytics/spellbook/blob/712907bf4636e6722df718e2766c2dab9f0a6311/models/labels/addresses/dao/identifier/multisigs/labels_dao_multisig_ethereum.sql#L1-L5

**Comment by jeff-dude** [comment]
tagging @andrewhong5297 to see if he can help move this forward
