### ISSUE TITLE
mo data: dex.offers

### ISSUE THREAD

**Issue by denverbaumgartner** [duneanalytics/spellbook#3224]
really starting this as a later to-do for myself with the hope that someone else finds it interesting enough to get to before i can 🤷 

we now have `dex.offers` which currently only collects limit order data. it would be 🔥 if we also collected historical price data from AMMs. this would be useful for checking historical prices, depth, etc. maybe this already exists somewhere? if so, please lmk 🙏 

in short, at a specific block, what was the liquidity curve of the AMM. i think for practical purposes, we will want to map this to a predetermined bin size through which to replicate this curve as offers. this is a pretty important open question, and really comes down to how much data we want this to store... 

my next goal on this front will be to include close data for the existing offer data from rubicon (block_number, reason: cancel / filled, maybe gas cost(?), etc). with this we can recreate the order book at any block on any network and have full [level 3 order book data](https://www.machow.ski/posts/2021-07-18-introduction-to-limit-order-books/#level-3-l3). @Hosuke figured you may find this interesting 🖖 

i also briefly talk about this idea here #3109 

@jeff-dude if you have any thoughts on any of this, all are appreciated. i think the major thing i don't know as mentioned above is the size at which to bin an AMMs curve, this really will impact the size of the data being created 🦖

**Comment by jeff-dude** [comment]
closing to move convo to #3228
