### ISSUE TITLE
[BUG] incorrect usd_amount in dex_aggregator.trades for CoW Swap router txn

### ISSUE THREAD

**Issue by blairmason** [duneanalytics/spellbook#3292]
### Description
I noticed some incorect usd_amount values in **dex_aggregator.trades** for CoW Swap router txns

### Current behavior
Using the query below, it shows that 2,486.34 USDC was swapped for 996,873,258,259 STG and the usd_amount for the swap was calculated to be $997,867,140,898 when it should really be closer to $2,486. The "to" address for this aggregator swap is a CoW Swap router address. 

```
SELECT
  *
FROM
  dex_aggregator.trades
WHERE 
  tx_hash = 0xad7d5814544440bdcb22760f8f2f0594958e9e6417249d96d92bf78cd05a80f5
    AND tx_to = 0x9008D19f58AAbD9eD0D60971565AA8510560ab41
```

### Expected behavior
The usd_amount should be nearly 1:1 with the USDC amount, which was 2,486.34.

### Impacted model(s)
I am sure the root cause is more upstream, but I identified the issue in the following table:
```
dex_aggregator.trades
```

### Possible solution
Price swap based on the token that we have higher confidence in the pricing for (i.e. USDC in this case)

**Comment by jeff-dude** [comment]
@blairmason thank you for raising the issue. this falls into the same bug as #3030 which is still open. for short term fix, we will add to tx exclusion list.
