### ISSUE TITLE
[BUG] Duplicates in odos trades

### ISSUE THREAD

**Issue by ytoast** [duneanalytics/spellbook#3309]
### Description

Some context: This is related to https://github.com/duneanalytics/spellbook/pull/2853. This is a known issue but I thought I'd document it here since I spent some time looking at it. I was looking into this as I noticed that the [uniqueness check for odos_avalanche_c_trades](https://github.com/duneanalytics/spellbook/blob/05544a9a4a7c33ffe74026fccbeb16aa34f25b7f/models/odos/avalanche_c/odos_avalanche_c_schema.yml#L15) is failing. Example [here](https://github.com/duneanalytics/spellbook/actions/runs/4915383239/jobs/8777815949?pr=3306).

Main reason:
1. **Odos performs batch swaps**. Each swap transaction here is the equivalent of multiple swap trades in the more "traditional" swap protocols. For example, Odos will allow users to swap token_A to token_B and token_C in a single swap trade. Compare this to something like Uniswap, where swapping token_A to token_B and token_C can only take place in 2 swap trades. This introduces complexity into the current logic used to normalise the swaps table

### Current behavior

There are 2 problems in the current table:
1. incorrect `token_bought_amount` - USDC has the wrong token_bought_amount
2. incorrect `token_sold_amount` - the sum of both rows should be 12.2
https://dune.com/queries/2452828
<img width="700" alt="image" src="https://user-images.githubusercontent.com/52529078/236859020-3464f47a-2688-466c-b8f6-7bda32e5f826.png">

|token_pair|token_bought_amount|token_sold_amount|
|--|--|--|
|USDC-WAVAX| 0.350273 |12.2|
|BTC.b-WAVAX| 0.00350273 |12.2|

### Expected behavior

Source of truth: https://snowtrace.io/tx/0x48bb32dc44006204e851bac988260b779918e1f4bcdddb86102f36ecb5b68846
|token_pair|token_bought_amount|token_sold_amount|
|--|--|--|
|USDC-WAVAX| 105.245739 |6.2242610707|
|BTC.b-WAVAX| 0.00350273 |5.975738929258659482|

### Impacted model(s)

```
odos.avalanche_c.trades
```

### Possible solution

There are a few changes to be made:
1. Fix https://github.com/duneanalytics/spellbook/blob/main/models/odos/avalanche_c/odos_avalanche_c_trades.sql to ensure that accurate `token_bought_amount` and `token_sold_amount` are reflected
  * It is easy to fix the token_bought_amount as this information is reflected in the Swap event
  * It is slightly trickier to fix token_sold_amount - one way is to look into the token transfers table to find the right attribution
3. Fix duplicate check
  * It is easy to fix this by adding token_pair into the uniqueness check

**Comment by Hosuke** [comment]
Some related discussion: https://github.com/duneanalytics/spellbook/pull/2853#issuecomment-1450421552

**Comment by ytoast** [comment]
Thank you Hosuke! I looked into it again and wanted to summarise some of my findings for anyone who wants to brainstorm on the issue.

Because of batch swaps, there are 4 different scenarios:

1. 1 to 1 swap ([example](https://snowtrace.io/tx/0xcc1b98f6ea4297895baec4b5b2671b64df5217ccb6ccc6b6aa1451013baadc1d))
1. 1 to many swaps (in the example I first listed above)
2. many to 1 swap ([example](https://snowtrace.io/tx/0x2df37510cafd104ab2cc13226d3dad6e5238dfa99d6df9c540344989d5c2012b))
3. many to many swaps ([example](https://snowtrace.io/tx/0x92f06db6c525ad25faa302936cb4f5cbd436ca5278e1be7f51252db161380df1))

**Questions for discussion:**
* What is the most ideal way to represent this information in the trades table? 
* Should each row in the trade table represent a single swap (from the user perspective)? 
  * If yes, the table schema will need to change to allow us to store multiple tokensIn, tokensOut. This will mean that odos.trades will need to be removed from dex.trades
  * If not, what should each row represent? A distilled version of tokens transfers? Sort of like what I mentioned in the "expected behaviour" above

**Comment by Hosuke** [comment]
Ideally, each dex.trades record has its own unique_key `['block_date', 'blockchain', 'project', 'version', 'tx_hash', 'evt_index', 'trace_address']`. The most important field in this case would be `evt_index`.

If you look at logs of example closely, you will notice/find `Swap` events, the index of these events are ideal evt_index.

eg. https://snowtrace.io/tx/0x92f06db6c525ad25faa302936cb4f5cbd436ca5278e1be7f51252db161380df1#eventlog
[12, 15, 18] are swap events.

Maybe odos trades are hard to fit into general case.

**Comment by jeff-dude** [comment]
odos trades have been excluded from prod for awhile due to duplicates. anyone is welcome to open a PR to fix and fit into the sector-level structure. closing this for now.
