### ISSUE TITLE
[BUG] Miscalculated Paid Mint in nft.mints

### ISSUE THREAD

**Issue by MSilb7** [duneanalytics/spellbook#3336]
### Description

(warning: i've spent 0 time in nft.trades and nft.mints)

I was pulling paid mints, and found a few cases where a platform would have a veeeery small paid mint #. In one that I checked on Etherscan, it's not obvious that there was a payment. I wonder if there's some bug in the query that calculates the usd amount for nft.mints

Example transaction: https://etherscan.io/tx/0x4271c75d3efc66940696b1119bbef702189d273539ec4fae23d56c812a44efd9

In nft.mints, this shows a $3026.62745 mint price, but etherscan shows 0 payment.

### Current behavior

Apparent free mint has an amount_usd in nft.mints

### Expected behavior

This transaction shows as a free mint.

### Impacted model(s)

```
nft.mints
```

### Possible solution

Unclear without going deep in the mint models, but maybe something isn't being joined correctly?

**Comment by jeff-dude** [comment]
@0xRobin do you mind giving this a quick look? you're welcome to close it, if no longer an issue.

**Comment by 0xRobin** [comment]
closing as the above example correctly shows `amount_raw = 0` now.
