### ISSUE TITLE
Bug in erc20 transfer tables

### ISSUE THREAD

**Issue by 0xBoxer** [duneanalytics/spellbook#3431]
This `"from"` somehow gets interpreted as the literal value `from` instead of referencing the column `from`.
Seems to be an inconsistency in spark with treating double quotes as column name or value alternatively.

https://github.com/duneanalytics/spellbook/blob/fbf7473eb2036c19fbcca927a3271507f481ac79/models/transfers/bnb/bep20/transfers_bnb_bep20.sql#L23

Demonstrated in this query

https://dune.com/queries/2499768

This issue also pertains to the optimism and polygon versions of this Spell.

First reported in Discord here: https://discord.com/channels/757637422384283659/757641002138730588/1108775837009985616

**Comment by 0xRobin** [comment]
really strange, I can't seem to reproduce it on Dune.

**Comment by 0xBoxer** [comment]
in the 5 minutes I spent on this, it seemed like if from was used in the query before, this happened, but otherwise it was fine, but take that with a grain of salt, just braindumping here

**Comment by davidcheongyl** [comment]
hey folks is there a timeline for when this will be fixed?  am seeing these issues on:

- bnb, avalanche_c, polygon, optimism

eg :
select COUNT(*) from transfers_optimism.erc20
WHERE bytearray_length(wallet_address) != 20

**Comment by jeff-dude** [comment]
will be fixed in new transfers spells built natively on dunesql (see above linked issue)
