### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by max-morrow** [duneanalytics/spellbook#3499]
### Description
Incorrect column name in "Data explorer" in [genesis_balances spellbook](https://github.com/duneanalytics/spellbook/blob/main/models/balances/ethereum/genesis/genesis_balances.sql)

Currently working with the column name "address" (instead of "contract_address")

<img width="1709" alt="Screenshot 2023-06-09 at 11 30 06" src="https://github.com/duneanalytics/spellbook/assets/29593597/00e50f82-6c04-4969-857a-f27393fe18b3">
<img width="803" alt="Screenshot 2023-06-09 at 11 30 21" src="https://github.com/duneanalytics/spellbook/assets/29593597/7d402efc-7146-40d0-aff8-76e1c803e36f">
<img width="1708" alt="Screenshot 2023-06-09 at 11 30 48" src="https://github.com/duneanalytics/spellbook/assets/29593597/b3136753-d4f2-4a16-b2f9-70cc9069f4e2">

**Comment by jeff-dude** [comment]
this appears resolved. i see `address` in data explorer and table/spell code.
