### ISSUE TITLE
[BUG] oneinch_ethereum.trades doesn't work

### ISSUE THREAD

**Issue by SohnKirche** [duneanalytics/spellbook#3908]
### Description
when I want to get the latest 10 txs using oneinch_ethereum.trades. it threw an error. the error msg I got was **_“Failed analyzing stored view ‘delta_prod.oneinch_ethereum.trades’: line 30:5: column 11 in UNION query has incompatible types: uint256, decimal(38,0) at line 2._**

here is my query.
```
select * from oneinch_ethereum.trades
order by block_time desc
limit 10
```

**Comment by jeff-dude** [comment]
thank you @SohnKirche -- i've opened a PR to fix on another repo.
