### ISSUE TITLE
[BUG] dex.trades missing some curve pools

### ISSUE THREAD

**Issue by sschuldenzucker** [duneanalytics/spellbook#3927]
### Description

Some Curve.fi pools are missing in `dex.trades`, for instance this one: 0xae34574ac03a15cd58a92dc79de7b1a0800f1ce3 (FRAX - USDP)

### Current behavior

- The following query yields no results, but it should yield some: `select * from dex.trades where project_contract_address = 0xae34574ac03a15cd58a92dc79de7b1a0800f1ce3`
- The following query only shows some pools and the total is too low (compared to the curve.fi website): https://dune.com/queries/2811524

### Expected behavior
Should be showing all pools from here: https://curve.fi/#/ethereum/pools (search for "USDP")

### Impacted model(s)
```
dex.trades
```

### Possible solution

Not sure. The one that *is* shown is a factory pool, so the problem doesn't seem to be with that.

**Comment by andrewhong5297** [comment]
there is a PR coming to add these in soon!
