### ISSUE TITLE
[BUG] dex.prices seems to miss some tokens?

### ISSUE THREAD

**Issue by andrewhong5297** [duneanalytics/spellbook#4038]
### Description
Was trying to use dex.prices and realized some tokens like HVND are missing even though they show up when I run the query in app. 

### Current behavior
You can see the prices show up here in this query: https://dune.com/queries/2843856

### Expected behavior
These rows in the app query linked above should show up in the table. Maybe it just needs a full rerun?

### Impacted model(s)

```
dex.prices
```

### Possible solution
I think it just needs a full rerun - possibly some timing dependency with dex.trades getting rebuilt but then dex.prices not getting rebuilt so the trades never registered upstream, idk really.

**Comment by kvtoraman** [comment]
It's missing USDC token as well on arbitrum (`0xaf88d065e77c8cc2239327c5edb3a432268e5831`)

**Comment by m-r-g-t** [comment]
I think this was fixed as part of the migration to DuneQL - right?

**Comment by jeff-dude** [comment]
yes, this appears to be fixed
```
select *
from dex.prices
where contract_address = 0x320d83769eb64096ea74b686eb586e197997f930
limit 10
```
