### ISSUE TITLE
[BUG]layerzero.send table  no latest data

### ISSUE THREAD

**Issue by niyuelin1990** [duneanalytics/spellbook#4090]
### Description
why  dune layerzero.send table  no latest data

now（8.16 6:50 UTC）， https://dune.com/queries/2738281  no latest data (the last data is  2023-08-15 18:34 )

https://github.com/duneanalytics/spellbook/tree/main/models/layerzero

**Comment by jeff-dude** [comment]
closing due to #4102 where bug is tracked
