### ISSUE TITLE
[BUG] Unable to query data from table `balances_ethereum.erc20_day`

### ISSUE THREAD

**Issue by longcnttbkhn** [duneanalytics/spellbook#4216]
### Description
Hi guys, I want to query from table: `balances_ethereum.erc20_day` by using query: `select * from balances_ethereum.erc20_day limit 10;` but it isn't working.

### Current behavior
`Error: Line 1:15: Failed parsing stored view 'delta_prod.balances_ethereum.erc20_day': line 6:79: mismatched input '1'. Expecting: '%', '(', ')', '*', '+', ',', '-', '->', '.', '/', 'AND', 'AT', 'OR', 'ORDER', 'OVER', '[', '||', <predicate>, <string> at line 1, position 15 [Execution ID: 01H9775BFCE2EDQQ1851RQAAQV].`

### Expected behavior
Balance of erc20 tokens in all wallets.

### Impacted model(s)
```
balances_ethereum.erc20_day
balances_ethereum.erc20_hour
balances_ethereum.erc721_day
balances_ethereum.erc721_hour
balances_ethereum.erc1155_day
balances_ethereum.erc1155_hour
```

### Possible solution
I think the cause of this problem is because we are using `explode` to Generate series and it doesn't work in DuneSQL, see detailed description here: https://dune.com/docs/query/syntax-differences/. My solution was to switch to using unnest:

Current code uses explode:

```
days as (
        select
            explode(
                sequence(
                    to_date('2015-01-01'), date_trunc('day', now()), interval 1 day
                )
            ) as day
    )
```

New code uses unnest:

```
 days as (
        with list_day as (select sequence(date('2015-01-01'),  date(now()), interval '1' day) as day)

        select u.day from list_day cross join unnest(day) as u(day)
    )
```

**Comment by jeff-dude** [comment]
yeah, that is likely part of the problem. since these are views, they run the underlying sql every time, and the spark syntax won't work on dunesql.

this is a known issue and actually believe we will be working on it internally soon to get back up and running on dunesql.

**Comment by jeff-dude** [comment]
there is an open PR attempting to migrate:
https://github.com/duneanalytics/spellbook/pull/4074

we will look to get this finalized asap 🙏

**Comment by jeff-dude** [comment]
please follow along the effort ongoing to rebuild transfers/balances on dunesql engine natively
