### ISSUE TITLE
[BUG] dex.trades 0x API V3 (token bought/sold address)

### ISSUE THREAD

**Issue by bh2smith** [duneanalytics/spellbook#4347]
[This query](https://dune.com/queries/3027500) shows three examples of records in dex.trades that have invalid token bought/sold address (`0x00000000000000000040` -- TOO SHORT!). Here are a few sample transactions:

1. https://etherscan.io/tx/0xcbfbc3d7493c9b0193937a5cdd93a3bad396d402cd71ba3e7c0138000681ac95
2. https://etherscan.io/tx/0x69515dfe0638d46c409bbc0c7ebd163f6abf622f187b457a69e1e0345a2a869e
3. https://etherscan.io/tx/0x91df304bf4a2d95b0b8a079a17f88cce1828cb9ac35add5566c9f0baa1f079d6

The entire issue seems to revolve around this NFT token: 
https://etherscan.io/token/0x401b23f374df842d36c1918e1401b47d1e65317a

Probably a decoding error related to the NFT trades. 

<img width="986" alt="Screenshot 2023-09-15 at 5 19 31 PM" src="https://github.com/duneanalytics/spellbook/assets/11778116/ed90e8c8-7b14-4cf1-a6a2-14802639464c">

**Comment by jeff-dude** [comment]
this appears to be resolved
