### ISSUE TITLE
[BUG] delegate.defisucks.eth not in labels.ens table

### ISSUE THREAD

**Issue by m-r-g-t** [duneanalytics/spellbook#4525]
### Description
I have found another instance of an ENS domain not decoding properly in ENS labels.

### Current behavior
The event is collected successfully, but the table does not resolve it, ergo not propagating to the labels.ens table.

### Expected behavior
Correct resolution of this ENS name.

### Possible solution
I believe the issue to be within two tables deeper in the ENS labels stack - namely, updating ens.node_names + ens.view_registrations tables

**Comment by jeff-dude** [comment]
thank you for raising. are you able to open a PR to attempt to fix the spell(s)?

**Comment by nyssarex** [comment]
Hi, guys. I am just starting to dive into spellbook and dbt by experience, and found this bug as good one to start. So I have looked into this spells and found that they are not updated with new tables( ETHRegistrarController_4_evt_NameRegistered and ublicResolver_v2_evt_AddrChanged) . If i understand it correctly that should be enough to update spells. Should i create PR?

**Comment by jeff-dude** [comment]
> Hi, guys. I am just starting to dive into spellbook and dbt by experience, and found this bug as good one to start. So I have looked into this spells and found that they are not updated with new tables( ETHRegistrarController_4_evt_NameRegistered and ublicResolver_v2_evt_AddrChanged) . If i understand it correctly that should be enough to update spells. Should i create PR?

yes plz & link it back to this issue. thank you!

**Comment by nyssarex** [comment]
https://github.com/duneanalytics/spellbook/pull/4812 Here we go, was not available to add samples from updated table to bootstrap csv file, as do not have upgraded plan. The rest works fine i guess

**Comment by jeff-dude** [comment]
> We reverted PR, cause it failed to compile, after merging. Previously, i face this error as well locally. Got fixed, after I did dbt clean and started again from already synced repo. As for now if i try to add this source and update spells it compiles fine ![image](https://user-images.githubusercontent.com/69467191/283837338-58f90704-4e6e-4f88-9cf0-99f2b36c025a.png)

yes, thank you for paying close attention. it's odd that it compiled fine in CI tests, but failed instantly in prod. i will try to get this pushed again shortly.

**Comment by jeff-dude** [comment]
okay, looks like i found the bug. the schema was declared twice in the source file, so dbt must've looked at the second instance only and missed the sources in the first one. i removed the duplicate. it's odd that my local setup and prod found the issue, but CI tests didn't. maybe its "random" in terms of when it picks which of the two schemas in the file to look at?

anyway, we *should* be good now

**Comment by m-r-g-t** [comment]
Hey @jeff-dude - I've tested it out, and I don't think this fixed the issue.

Basically, within one of the ENS contracts, there is a note by 0xRob saying that the queries only work for domains and not subdomains under the newer ens contracts.

I believe that to be the source of the issue as to why wonderland's delegate doesn't appear properly

**Comment by m-r-g-t** [comment]
So I don't believe this bug to be closed

**Comment by jeff-dude** [comment]
> So I don't believe this bug to be closed

how do you recommend we proceed, other than just reopening this issue? i personally don't have time to dig into it deeper at the moment
