### ISSUE TITLE
[Request] Relationship tests with `.info` on sector wide spells

### ISSUE THREAD

**Issue by hildobby** [duneanalytics/spellbook#4631]
There are more and more projects in every sector and it's becoming hard to keep up with high level information on each of those (For example I don't know a lot of the DEXs in `dex.trades`). So I've created `.info` spells for each sector I've worked on [`evms`, `dex`, `nft`, `airdrop`, `staking`, `social` ([WIP](https://github.com/duneanalytics/spellbook/pull/4588))]. Those contain 1 row of info for every project in sector spells. You can then join on it using the `project` column (`blockchain` in `evms` sector & `entity` in `staking` sector). This allows for an easily accessible table with high level info. I started all those tables with at least `name` (properly capitalised project name) & `x_username` (project's official twitter). Those allow me to easily capitalise names in queries I showcase, and to easily find the project's twitter if I need more info (Twitter seemed to me like the easiest thing to point to, easier to find the rest from there).

I've also made some containing more info:
- [evms.info](https://github.com/duneanalytics/spellbook/blob/main/models/evms/evms_info.sql) contains all those which I use regularily: `chain_id`, `chain_type`, `rollup_type`, `native_token_symbol`, `wrapped_native_token_address`, `explorer_link`, `first_block_time`, `codebase`, `data_availability` (can filter for chains based on some params, easily find the chain's WETH/WBNB/WAVAX... address, find the native token's symbol, also get explorer links when joining, etc)
- [airdrop.info](https://github.com/duneanalytics/spellbook/blob/main/models/airdrop/airdrop_info.sql) contains `eligible_addresses`, `airdropped_total`, `circulating_supply_on_drop`, `max_supply`, `token_issued_by_protocol`, `x_username`, `airdrop_start` & `airdrop_end`. When comparing airdrop stats or looking at any airdrop, it's nice to have easily accessible context. I started making those info spells when I realised airdrop.info was going to be pretty hard to fully fill in (hence why it's still mostly NULLs). 

I also invite anyone to contribute and add new columns as they see fit. Some examples of cool stuff that I would love to have handy: `website_link` (project's website),`docs_link` (link to project's documentation), `has_token` (if a token is tied to the project), `had_airdrop` (if project had a past airdrop)

For sectors like `evms` & `airdrop` I already have/am working on having those relationship tests to ensure any additional project to the spells there need to be accompanied with their one liner in the `.info` spell.

What do you guys think about also applying those relationship tests on dex.[trades, flashloans, sandwiches] & nft.trades? I've already filled info for all projects currently in those sectors and can finalise my PRs with the relationship tests if you guys agree ([dex.info PR](https://github.com/duneanalytics/spellbook/pull/4589), [nft.marketplace_info PR](https://github.com/duneanalytics/spellbook/pull/4594)).

It's also a solid test to have to ensure we know what are all the project values in each sector. CI tests of the `dex.info` spell PR surfaced some DEX misspelled on one of its chains for example: https://github.com/duneanalytics/spellbook/pull/4589/files

I'm not saying a relationship test with `.info` spell should be mandatory in each sector, it doesn't work for some. For example sometimes all info I have on  a staking entity is its tag name (like individual stakers that only have ENS doxxed) so I don't have any info for the info spell, hence why staking sector lacks that relationship spell.

@jeff-dude @0xRobin @Hosuke @MSilb7 @henrystats @pandajackson42

**Comment by Hosuke** [comment]
In my opinion, the `.info` spells should comprehensively encompass all the meta-data of existing spells within the spellbook. Essentially, they could serve as an overview or catalog of the spellbook, providing quick access to vital information and significantly aiding navigation and understanding of the contents. This approach is undoubtedly beneficial.

Furthermore, by integrating `relationship` tests, we are essentially establishing a form of bonding that ensures synchronization within the `.info` lists. This method not only maintains the integrity of the data but also reinforces the interconnectedness of the information across different spells. It's a strategic move towards keeping the spellbook not only updated but also consistent in its relational mappings.

**Comment by 0xRobin** [comment]
> It's also a solid test to have to ensure we know what are all the project values in each sector. CI tests of the dex.info spell PR surfaced some DEX misspelled on one of its chains for example: https://github.com/duneanalytics/spellbook/pull/4589/files

Yess :100:

Let's add a `not_null` test to the `project` and `name` columns so we always have at least this information (if no descriptive name is known they can be identical).
Probably also a `unique` test on `project` so we never have any duplicates.

**Comment by jeff-dude** [comment]
thank you for bringing the conversation here into an issue, as it spans across various sectors and multiple spells.

in general, i think this could be a nice value-add test for the sector spells -- as well as the additional tests mentioned by rob. i also think we will benefit from implementing in a bit of an organized fashion, especially since we're in the process of redesigning both dex/nft right now.

to stay organized, i propose we remove the test additions in #4589 and keep that PR to simply cleaning up the `.info` spell. then we can take the learnings from here and apply the tests in the PR used for redesign of dex trades at #4533. similar idea for nft would be good. if we're asking contributors to take additional steps on new dex/nft spells, i think it'd be good to wait to include that in the revamped submission process post redesign.

as for the other sectors, we may be able to implement sooner, as some may already be in a better spot design-wise.

**Comment by jeff-dude** [comment]
in the recently merged dex beta redesign, this test was included:
https://github.com/duneanalytics/spellbook/pull/4533/files#diff-fe65d57c84dd57310c191451fc6abc8715ce679dfead7064e2bce014bf640400R23-R29

do you have any additional feedback on this @hildobby (for dex only atm)?

**Comment by jeff-dude** [comment]
closing due to usage in new dex sector lineage. any new sectors built can follow suit.
