### ISSUE TITLE
[BUG] No Valeria (VAL) Data In prices.usd

### ISSUE THREAD

**Issue by nathanglb** [duneanalytics/spellbook#4686]
### Description
I'm not sure how long it takes to backfill once the PR is merged, but VAL data should now be available for prices.usd and there are no records a couple hours post-merge.

0x456f931298065b1852647de005dd27227146d8b9 (Polygon)
0x011e128ec62840186f4a07e85e3ace28858c5606 (Mainnet)

### Current behavior

No data available.

```
SELECT
  *
FROM prices.usd
WHERE
  contract_address = 0x456f931298065b1852647de005dd27227146d8b9 OR
  contract_address = 0x011e128ec62840186f4a07e85e3ace28858c5606
limit 10
```

### Expected behavior
I expected that the coinpaprika API would be used to backfill pricing for these tokens.

### Impacted model(s)

```
prices.usd
```

### Possible solution
Will this backfill automatically at some point, or is a manual action needed?

**Comment by jeff-dude** [comment]
both are now there. it can take some time to backfill.
