### ISSUE TITLE
[BUG] balances_polygon.matic_latest may not correct

### ISSUE THREAD

**Issue by abcfy2** [duneanalytics/spellbook#4706]
### Description

Here's the result of `select * from balances_polygon.matic_latest bm where bm.wallet_address = 0x69155E7cA2E688ccDc247f6c4DDF374b3ae77Bd6`

wallet_address | token_address | amount_raw | amount | amount_usd | symbol | last_updated
-- | -- | -- | -- | -- | -- | --
0x69155e7ca2e688ccdc247f6c4ddf374b3ae77bd6 | 0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270 | 4.0069485662424195e+21 | 4006.9485662424177 | 2546.1633760873833 | MATIC | 2023-10-30 02:51

But in fact this account in polygon matic should be `5,019.245565734667757417` https://polygonscan.com/address/0x69155e7ca2e688ccdc247f6c4ddf374b3ae77bd6

![图片](https://github.com/duneanalytics/spellbook/assets/5327677/7fe42528-f1b6-482d-bba4-1355b5385f42)

### Current behavior

`balances_polygon.matic_latest` not the same as polygon scan result

### Expected behavior

`balances_polygon.matic_latest` should correct

### Impacted model(s)

```
balances_polygon.matic_latest
```

**Comment by jeff-dude** [comment]
we are in the process of rebuilding transfers / balances natively on dunesql engine. please follow along in the repo as those continue to get built out. for now, you will see inaccurate/outdated data on many blockchains.
