### ISSUE TITLE
Rebase token balances

### ISSUE THREAD

**Issue by aalan3** [duneanalytics/spellbook#4735]
It was pointed out by @grkhr in https://github.com/duneanalytics/spellbook/issues/4521#issuecomment-1798393445 that using the transfers table to create balances for tokens that use staking will not work:

>Btw there are a lot of tokens which supports staking option and there are no easy way to properly determine balance of them.
> 
> For example stETH (which is huge) balanceOf implementation is custom: https://github.com/lidofinance/lido-dao/blob/master/contracts/0.4.24/StETH.sol#L166
> 
> E.g. for 0x41C59bf14D1407311AAa1B91EEE6D2d441a3Ec52:
> Dune balance based on evt_Transfer: 9,963 stETH ($18,701,257)
> True balance on etherscan: 10,430 stETH ($19,577,849)
> The diff is huge 😬 And I have no idea how to deal with that (and should we?)

And in the same issue by @henrystats  https://github.com/duneanalytics/spellbook/issues/4521#issuecomment-1798617600: 

> I believe stETH is a rebase token and those were filtered from the balances spell originally, and still are, stETH just wasn't added to the rebase tokens list hence why it's still showing up.
> 
> Getting stETH balances is a very long process, even on dune itself, I've not seen any query that gets the balances completely accurate (i.e the correct exact balance at the time), there has been some workaround that the stETH team created themselves, Hildobby also worked on one and that seems to be the approach to getting stETH balances for non contract addresses.
> 
> I'd advise we filter them for now.. 

As @henrystats suggests I think we should filter these out for now. 

We need to investigate if it's possible to create a spell for this in a different way. One way could be to try to copy the calculation in the contracts and do it directly in the spell, but this might be a lot of work and difficult to scale. Open to suggestions for how to approach this.

Related issue: https://github.com/duneanalytics/spellbook/issues/4523

**Comment by grkhr** [comment]
I'd suggest to not to filter these tokens from transfers. Let it be in the final spell. Anyway usd balances will be not 100% correct, but we'll cover at least of ~95% stETH balances from transfers.

**Comment by aalan3** [comment]
>I'd suggest to not to filter these tokens from transfers. Let it be in the final spell. Anyway usd balances will be not 100% correct, but we'll cover at least of ~95% stETH balances from transfers.

I was referring to filtering these from balances but not transfers. But do you think we should keep it in balances as well?

**Comment by grkhr** [comment]
I think yes, but it's debatable. Maybe add a `token_type` attr with "rebase" value or smth to leave the choice to the users.

**Comment by hildobby** [comment]
All approaches I know for handling rebasing tokens are to use their respective oracle for the conversation rate and applying it daily (or whenever that rebase takes place) but I haven't looked in a while. So idk any global solution here. It may necessitate having a spell for whitelisted rebasing tokens (only important ones) where for each, its oracle call/evt table is mapped. That is with the assumptions they all work like this, which Im not sure thats true.

Gonna DM the lido guys to see if they have a solution here

**Comment by hildobby** [comment]
So, like I thought, `stETH` uses an oracle event table for rebalances once a day. What could be done is having a list of mapping for the more important tokens where the contract address is mapped to its corresponding oracle table.

Only thing is that `stETH` had that oracle changed once, but that could easily be fixed with a view that includes both oracles. If someone already wants to start testing (but also for future reference), `stETH` used to use `lido_ethereum.LegacyOracle_evt_PostTotalShares` and now uses `lido_ethereum.steth_evt_TokenRebased` as its rebasing oracle.

**Comment by hildobby** [comment]
Here's a query courtesy of Sam from the Lido analytics team showcasing how those oracles can be used to correct balances: https://dune.com/queries/3181757/5313658

**Comment by grkhr** [comment]
thx! looks easier than i thought.

**Comment by jeff-dude** [comment]
closing in favor of #5123
