### ISSUE TITLE
[REQUEST] Add zora network to NFT spellbooks

### ISSUE THREAD

**Issue by kotte34723** [duneanalytics/spellbook#4736]
Now that zora network data will be available on Dune, making a request to include it into the NFT sector spellbooks, so users can easily access L1/L2 data in a single location

**Comment by jeff-dude** [comment]
pulling in @0xRobin here

my understanding is that we have zora data on ethereum blockchain in `nft` sector spells, but maybe not the new zora blockchain data?

**Comment by kotte34723** [comment]
@jeff-dude that's correct!

**Comment by jeff-dude** [comment]
@kotte34723 are you comfortable trying to open a PR and build it out? or do you need a wizard with more expertise to help?

**Comment by kotte34723** [comment]
@jeff-dude  I'm actually on the zora team, as the sole data person, so it would be immensely helpful if a wizard could pick this up.

**Comment by jeff-dude** [comment]
> @jeff-dude I'm actually on the zora team, as the sole data person, so it would be immensely helpful if a wizard could pick this up.

nice! sounds good. we'll let @0xRobin respond, in terms of if it's in motion already or if we can find someone to help ya out.

**Comment by kotte34723** [comment]
thanks, definitely appreciate it!

**Comment by 0xRobin** [comment]
hey @kotte34723, what specific nft data are you looking for?

**Comment by kotte34723** [comment]
@0xRobin ideally, we could a similar table to `nft.mints` -this would be the top priority.

**Comment by kotte34723** [comment]
@hildobby yep, this is exactly what we need

**Comment by kotte34723** [comment]
Does this also mean that blockchain=zora will work on the `nft.mints` table now?

**Comment by franaguila** [comment]
hey! just reading through this thread - would be great to have the spellbook table `prices.usd` include zora data as well. (currently work on data at splits / splits.org)

**Comment by hildobby** [comment]
> hey! just reading through this thread - would be great to have the spellbook table `prices.usd` include zora data as well. (currently work on data at splits / splits.org)

Other than WETH, what ERC20s do you need a price feed for? Made a PR to add those here (just WETH so far): https://github.com/duneanalytics/spellbook/pull/4831

**Comment by kotte34723** [comment]
@hildobby mind trying to land this today? We are trying to publish some dashboards and need this data. also, how much work is it to do the same thing for Base? I can create a separate PR for that too cc @0xRobin

**Comment by franaguila** [comment]
> > hey! just reading through this thread - would be great to have the spellbook table `prices.usd` include zora data as well. (currently work on data at splits / splits.org)
> 
> Other than WETH, what ERC20s do you need a price feed for? Made a PR to add those here (just WETH so far): #4831

thanks! the most used tokens on zora chain would be great.

**Comment by hildobby** [comment]
> > > hey! just reading through this thread - would be great to have the spellbook table `prices.usd` include zora data as well. (currently work on data at splits / splits.org)
> > 
> > 
> > Other than WETH, what ERC20s do you need a price feed for? Made a PR to add those here (just WETH so far): #4831
> 
> thanks! the most used tokens on zora chain would be great.

idk what those are, feel free to share a list and Ill add them, only notable one I found was WETH (PR was merged so price feed is live there)

**Comment by kotte34723** [comment]
No worries, I understand the desire for it to be accurate. And yes, looking for "all mints where zora the protocol was used, across chains" 👍

**Comment by wminshew** [comment]
> idk what those are, feel free to share a list and Ill add them, only notable one I found was WETH (PR was merged so price feed is live there)

USDC, USDT, & DAI seem like good additions

**Comment by hildobby** [comment]
> > idk what those are, feel free to share a list and Ill add them, only notable one I found was WETH (PR was merged so price feed is live there)
> 
> USDC, USDT, & DAI seem like good additions

Have those been bridged? Can't see any relevant tokens that has been transferred > 100 times other than WETH
src: https://dune.com/queries/3237129
