### ISSUE TITLE
[Idea] Materialize chain-specific contract_mapping views

### ISSUE THREAD

**Issue by MSilb7** [duneanalytics/spellbook#4854]
### Description
In https://github.com/duneanalytics/spellbook/pull/4747, we refactored the `contract_mapping` spells, where two base tables are materialized before eventually joining with reference tables in a view for each chain. These chain-specific views also populate a cross-chain view.

Problem: The final base table still has millions of rows, and querying from the chain-level contract_mapping views can be slow ([example](https://dune.com/queries/3220489): the cross-chain version takes 2 mins to run on the large cluster). This makes the table hard to use, especially when joining to large source tables such as traces or logs.

**My question:** Does it make sense to materialize the chain-specific contract_mapping spells as a table (not incremental), so that we don't push the load to query runtime? Also, at that point would it make sense to materialize the cross-chain version? An update once per day (right after midnight UTC) should be sufficient.

### Current behavior
contract_mapping tables are slow to query

### Expected behavior
contract_mapping tables take < 1 second to query

### Impacted model(s)

```
contracts_<blockchain>.contract_mapping
contracts.contract_mapping
```

### Possible solution
Materialize the views in to tables / other dbt magic ideas?

**Comment by jeff-dude** [comment]
we can materialize all levels incrementally to keep in sync, we just need to consider what is joined in at each stage. i'd still recommend leaving out any metadata-driven joins to views at the end, if possible.

what is causing the slow query runtime? joins to base tables? if so, materialize those incrementally and leave out metadata. continue to join metadata in at the final stage(s).

**Comment by jeff-dude** [comment]
closing in favor of open PR to migrate to incremental
