### ISSUE TITLE
[Request] Automate ingestion of prices from Coinpaprika with a script

### ISSUE THREAD

**Issue by cryptokoryo** [duneanalytics/spellbook#5110]
Following up on a discussion on Discord:
Source: 
https://discord.com/channels/757637422384283659/1187733580676333578/1188330212107227166

Context: 
"
Koryo: The current system of having to do a PR for every new token doesn't seem scalable considering the immense number of new tokens coming to market every day. Does this have to be hard-coded in that way on prices_tokens.sql spell? Can't it be (semi-)automated through a script?

jh: previously someone did it for the erc20_tokens, that can probably be explored as well , so this might be looked into? cc @jeff-dude 
"
I feel the current process of having to do a PR for adding a single token is a pain and could be avoided. Specially that until recently, many tokens/coins among the Top 100 projects by market cap were still missing (Some still do). 

Automating this through a script will unlock new possibilities for wizards. 

I'd be happy to somehow assist in the implementation of this with the help of the team. But I'm not sure what kind of script (language, pipeline, dependencies, etc.) is needed. 

I'm aware that this is probably gonna take some time. I'm ok with that. 
Is this something the team would be interested to implement?

**Comment by cryptokoryo** [comment]
Gm @aalan3 @jeff-dude 

The number of important projects with new listings is exploding, $STKR, $PANDORA, $ALT, etc. etc. 
Something like this would really help.

Any updates here? 
Thanks!

**Comment by jeff-dude** [comment]
> Gm @aalan3 @jeff-dude
> 
> The number of important projects with new listings is exploding, $STKR, $PANDORA, $ALT, etc. etc. Something like this would really help.
> 
> Any updates here? Thanks!

gm gm @cryptokoryo 

we're well aware of the pain points associated with prices at this time. we've started discussions internally on how to approach and solve this, whether it's different data provider (or multiple), onchain sources, using dex data to build prices, etc.

this will ideally be prioritized for our team in Q2 of this year, but nothing set yet. we will most likely not move forward with automating coinpaprika until we've analyzed the above options fully. however, we are happy to accept batch entries on prices as long as they pass CI on our side. if that means you build your own automated script and output to spellbook, that should be fine.

please stay tuned for an enhanced experience on prices 🙏
