### ISSUE TITLE
`dex.trades_beta` -- how to handle curve decimals logic

### ISSUE THREAD

**Issue by jeff-dude** [duneanalytics/spellbook#5214]
issue originally found while building new `amount_usd` design in dex lineage:
https://github.com/duneanalytics/spellbook/pull/5130#issuecomment-1895377596

first attempt at fixing from @tomfutago:
https://github.com/duneanalytics/spellbook/pull/5184

alternative attempt at fixing from @Hosuke:
https://github.com/duneanalytics/spellbook/pull/5195

for now, i will close both PRs so we can focus conversation within this issue. both will still be able to be referenced via the links above.

### issue overview
curve has added complexity relative to majority of dex's which feed into `dex.trades`. the specific piece of logic adding complications in the new design revolves around:
- what token to assign in bought / sold, when the 3CRV pool is involved, example on optimism [here](https://optimistic.etherscan.io/token/0x1337bedc9d22ecbe766df105c9623922a27963ec)
- the decimal values of tokens within the pool may vary (6 or 18), as well as the pool itself (18)
- existing code on ethereum [here](https://github.com/duneanalytics/spellbook/blob/main/models/curvefi/ethereum/curvefi_ethereum_trades.sql#L103-L104), which feeds `dex.trades` today, with a focus on decimal logic
- existing code on optimism [here](https://github.com/duneanalytics/spellbook/blob/main/models/curvefi/optimism/curvefi_optimism_trades.sql#L182-L183), which feeds `dex.trades` today, with a focus on decimal logic

in the new dex lineage, still in beta, this extra logic around decimals is missing since we decoupled the raw data from the enhancement metadata (tokens / prices), which contain the decimal values for dividing the raw amount into final amount. since we aren't overriding the decimal in the division to amount for curve, the `amount_usd` value is inflated to wildly high amounts (dividing by 6 rather than 18).

```
select blockchain, project, version, count(1)
from dex.trades_beta
where amount_usd >= 1000000000
group by blockchain, project, version
```
![image](https://github.com/duneanalytics/spellbook/assets/102681548/35d4983e-73ac-4dcf-872e-19856db048d1)

in the new dex lineage, we are **_not_** currently pulling through the fields from curve base level raw spells needed to write the correct amount logic in the final enhancement stage [here](https://github.com/duneanalytics/spellbook/blob/main/macros/models/_sector/dex/enrich_dex_trades.sql#L46-L47).

### optimism vs. ethereum
- optimism reads from decoded tables
- ethereum reads from raw base tables
- the logic for decimals is slightly different, although i'm assuming that's due to decoded vs. raw base and the logic is actually similar (again, assuming here)
- the positive sign is both handle logic needed for decimal assignments based on pools

do we need to consider refactoring one or the other to match how they read the data and assign this logic?

### options to move forward & fix
- in the final enrichment macro, left join back to curve base level raw data for each optimism/ethereum and pull the necessary fields to add the case logic within the amount calculations for decimal assignment
- pull the necessary fields all the way through to final enrichment stage, default to null for all other projects (can do this at the chain-level union to avoid editing all projects), apply logic as needed in enrichment, don't pull columns through to final `dex.trades_beta`
- use the logic from @Hosuke closed PR above, where if we ever see `usdc/usdt/dai` address in the `token_sold` field at the base level models, then override to the 3CRV pool token address instead (is that viable to show 3CRV as the token sold?)
- other ideas?

**Comment by Hosuke** [comment]
A few thoughts:
- Do we have to include `curvefi_*.MetaPoolSwap_evt_TokenExchangeUnderlying` events in the `dex.trades`? As the problems may only come from events from this specific source.
- Do we have decoded tables for `ethereum` now?
- Overriding decimals may be implemented in the `base_trades` level, as they are certain.
