### ISSUE TITLE
[BUG] SyncSwap trades are not being include in `dex.trades`

### ISSUE THREAD

**Issue by thetroyharris** [duneanalytics/spellbook#5594]
Not sure what is going on but PR #5528 was merged a few days ago and no trades are being displayed in `dex.trades` for SyncSwap on zksync. @Hosuke

**Comment by Hosuke** [comment]
> Not sure what is going on but PR #5528 was merged a few days ago and no trades are being displayed in `dex.trades` for SyncSwap on zksync. @Hosuke

I changed the `project` field to lowercased `syncswap` to keep consistent with other projects.

And they are under `dex.trades_beta` at the moment:
https://dune.com/queries/3523413
