### ISSUE TITLE
[POTENTIAL BUG] `token_id` and `number_of_items` sometimes missing from `nft.trades`

### ISSUE THREAD

**Issue by agaperste** [duneanalytics/spellbook#5628]
### Description
I was poking at `nft.trades` and saw some records with `token_id` and/or `number_of_items` being null — is this expected?
For null `token_id`, most of it is from solana, then outside of solana most is from bnb chain and for this project liquidify
Not a blocker for what I’m doing but wanted to flag it. 

### Current behavior

![image](https://github.com/duneanalytics/spellbook/assets/5827114/f37c8bf0-46f4-40b9-9890-989139ae6410)
![image](https://github.com/duneanalytics/spellbook/assets/5827114/d8cf44aa-86fa-4e43-a591-0013000c3b1c)

### Expected behavior

I am not 100% sure whether or not these two columns should be null?

### Impacted model(s)
```
nft.trades
```
more than 10k rows affected

**Comment by agaperste** [comment]
Hey @0xRobin, I flagged this to Jeff in team chat and he pointed me to raising an issue and tagging you 🙏 
Not a blocker for me but since it's nft.trades thought to flag it

**Comment by 0xRobin** [comment]
hey @agaperste,
`token_id` is expected to be null for solana in `nft.trades`. This is becuase they don't have numeric token IDs so we can't fit it into the main `nft.trades` schema. `nft_solana.trades` has all the info as it uses a different solana specific schema.
For liquidifty it seems that their source calls/event sometimes just don't surface this data.. :(
