### ISSUE TITLE
No records in dex_aggregator.trades

### ISSUE THREAD

**Issue by amalashkevich** [duneanalytics/spellbook#5688]
### Description

I submitted a PR which added Ethereum to the dex_aggregator.trades table some time ago which was merged https://github.com/duneanalytics/spellbook/pull/5530.
I also can see this code in the repository https://github.com/duneanalytics/spellbook/tree/main/models/odos

But when I run this query:
select distinct(blockchain) from dex_aggregator.trades where project='odos'

I only can see `optimism` as the result and no `ethereum`.
I checked the source, it is there and the query `select * from odos_v2_ethereum.OdosRouterV2_evt_Swap` shows data.

Could you help to figure out what is wrong?

### Current behavior
The query
```
select distinct(blockchain) from dex_aggregator.trades where project='odos'
```
returns 'optimism' only.

### Expected behavior
The query
```
select distinct(blockchain) from dex_aggregator.trades where project='odos'
```
returns 'optimism' and 'ethereum'.

### Impacted model(s)

```
dex_aggregator.trades
```

@jeff-dude @0xRobin

**Comment by jeff-dude** [comment]
thanks for raising.

looks like we never cleaned up full path for odos, as we had it excluded previously due to incorrect logic and prod failures. see the final `dex_aggregator` spell here:
https://github.com/duneanalytics/spellbook/blob/main/models/dex/dex_aggregator_trades.sql#L18-L21
and how only optimism is included:
https://github.com/duneanalytics/spellbook/blob/main/models/dex/dex_aggregator_trades.sql#L37

feel free to open PR to clean that up 👍 
you can also add `base` to `odos_trades.sql`?

**Comment by amalashkevich** [comment]
@jeff-dude thanks for the info.
I think I did it here https://github.com/duneanalytics/spellbook/pull/5718
But the test fails, not sure if this is my change, could you take a look?
https://github.com/duneanalytics/spellbook/actions/runs/8526776877/job/23356758978?pr=5718

**Comment by amalashkevich** [comment]
Hi @jeff-dude 
How can I see how the line 420 looks like? It says "Column 'block_month' cannot be resolved", but according to the schema, the column name 'block_month' is there.

13:47:25    Database Error in model dex_aggregator_trades (models/dex/dex_aggregator_trades.sql)
  TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 420:7: Column 'block_month' cannot be resolved", query_id=20[24](https://github.com/duneanalytics/spellbook/actions/runs/8555661196/job/23443588717?pr=5718#step:11:25)0404_134621_00008_qupjv)
  compiled Code at target/run/spellbook/models/dex/dex_aggregator_trades.sql
