### ISSUE TITLE
[BUG] bonkbot_solana.trades spellbook stopped indexing new records

### ISSUE THREAD

**Issue by whalehunting** [duneanalytics/spellbook#5689]
### Description
The `Bonkbot Solana Trades` spellbook, introduced in #5520 is not updating anymore. 

To reproduce:
```sql
SELECT
  *
FROM
  bonkbot_solana.trades
ORDER BY
  block_time DESC
LIMIT
  1
```

### Current behavior
The last indexed trade has a timestamp of `2024-03-26 12:51`

### Expected behavior
Trades should have a more recent timestamp by now, as the fee wallet still has activity every few seconds:
https://solana.fm/address/ZG98FUCjb8mJ824Gbs6RsgVmr1FhXb2oNiJHa2dwmPd/transactions

### Impacted model(s)
```
bonkbot_solana.trades
```

### Possible solution
-

**Comment by jeff-dude** [comment]
remember, the whole lineage is now alias `bot_trades` :)

updated query:
```
SELECT
  *
FROM
  bonkbot_solana.bot_trades
ORDER BY
  block_time DESC
LIMIT
  1
```

![image](https://github.com/duneanalytics/spellbook/assets/102681548/88a75e2b-f211-4047-9583-94d1be641c02)

**Comment by jeff-dude** [comment]
i imagine you'll use `dex_solana.bot_trades` for downstream dashboards?

**Comment by jeff-dude** [comment]
we have an automated process to drop spells in the metastore / data lake after removed from `main` branch, so i'd expected the `trade` alias spell to be gone soon

**Comment by whalehunting** [comment]
> remember, the whole lineage is now alias `bot_trades` :)
> 
> updated query:
> 
> ```
> SELECT
>   *
> FROM
>   bonkbot_solana.bot_trades
> ORDER BY
>   block_time DESC
> LIMIT
>   1
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/102681548/317490249-88a75e2b-f211-4047-9583-94d1be641c02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NzA4MjcsIm5iZiI6MTcxMTU3MDUyNywicGF0aCI6Ii8xMDI2ODE1NDgvMzE3NDkwMjQ5LTg4YTc1ZTJiLWYyMTEtNDA0Ny05NTgzLTk0ZDFiZTY0MWMwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QyMDE1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmVkNzIzYWU5MzBkMWRlM2M0MzY3Mzk2OWJhMThkNTIwNmEyMGQ5NzIyNDI0MTk2NTQzYTQ2M2UyNWViYWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KvRbXxdivwWe0acnUMmMVmbKNeifFqn4kkmWGggf-_Y)

oh ok that makes sense! thanks for pointing it out, didn't see that bonkbot was also changed :)
