### ISSUE TITLE
Database Error in model depin_revenue on local dbt compile

### ISSUE THREAD

**Issue by 0xRobin** [duneanalytics/spellbook#5744]
I'm getting 
```
09:23:02  Encountered an error:
Runtime Error
  Database Error in model depin_revenue (models/_sector/depin/depin_revenue.sql)
    failed to execute: HTTPConnectionPool(host='trino', port=1234): Max retries exceeded with url: /v1/statement (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd5d60afe80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```
When running `dbt compile`.

I believe this is due the use of `dbt_utils.union_relations` here:
https://github.com/duneanalytics/spellbook/blob/d2efb1f8cf2c30df79cdbfbe05e1b187d901d492/models/_sector/depin/depin_revenue.sql#L9-L13
which might require a database connection to work? :thinking: 

Are we able to rewrite this with a 'vanilla' union loop?

cc: @0xnirmal @Hosuke @jeff-dude

**Comment by tomfutago** [comment]
Yep, I'm getting this error too, thanks for looking into this!

**Comment by jeff-dude** [comment]
nice catch!
