### ISSUE TITLE
spell that starts from the hash

### ISSUE THREAD

**Issue by peonante** [duneanalytics/spellbook#5894]
Hi everyone, amazing project.

sorry for the noob question but it's not easy starting from scratch given the vastness of the project.

By chance, there is a spell that by having a hash it is possible to obtain simple information such as;

- chain
- wallet
- value

**Comment by jeff-dude** [comment]
hi @peonante 
check out balances spells in this directory:
https://github.com/duneanalytics/spellbook/tree/main/models/_sector/tokens/ethereum

you can also go back a level to find other chains. you can grab schema/table name in the sql files. these should provide token balances per address as they change

**Comment by peonante** [comment]
Thanks, I'll try to start from here
