### ISSUE TITLE
[BUG]Token amount decimals are off in dex_solana.trades for some Phoenix transactions

### ISSUE THREAD

**Issue by GeekLad** [duneanalytics/spellbook#6021]
### Description
I was working with `dex_solana.trades` and found that transactions on Phoenix for Bonk appear to be off by several decimal places.

### Current behavior
Here's a query you can run to isolate a specific transaction that exhibits the problem:

```sql
select
  *
from
  dex_solana.trades
where
  tx_id = '4QsGpqtobY2A1QoWCw3ioY1yzdZE31RXRsARPgt1egk2RFZMa1z1mpQwhf9QYLfGY9FqgM18eUgpBjCFz5jW5Xf5'
  and block_time >= timestamp '2024-05-28 19:59'
  and block_time <= timestamp '2024-05-28 20:00'
```
For the USDC-Bonk swap, it shows that only 128.9 Bonk were swapped.  It seems that all swaps in the `GBMoNx84HsFdVK63t8BZuDgyZhSBaeKWB4pHHpoeRM9z` exhibit this problem.  There may be other problematic phoenix markets as well.

### Expected behavior
128,900,000 should have been swapped.

### Impacted model(s)
```
dex_solana.trades
```

### Possible solution
I'm not sure how the phoenix transactions are loaded into this table.  If someone can point me in the right direction, I can take a look.

**Comment by jeff-dude** [comment]
@andrewhong5297 fyi, do you want to help look into this bug?

**Comment by andrewhong5297** [comment]
yeah they use custom decimals per market that are different from the actual token decimals. I can add this into https://github.com/duneanalytics/spellbook/pull/6093 to fix

**Comment by andrewhong5297** [comment]
I've fixed it, query here from test CI output https://dune.com/queries/3819568

**Comment by alexeyrodriguez** [comment]
@andrewhong5297 is this really fixed? When I run the query of the reporter, I see that the amount of Bonk swapped for USDC-Bonk is 0.01289 rather than the 128,900,000 that the reporter suggests.

**Comment by andrewhong5297** [comment]
The fix has not been merged yet, see this PR https://github.com/duneanalytics/spellbook/issues/6281
