### ISSUE TITLE
[BUG] tokens_solana.transfers not showing all transfers inside a transaction

### ISSUE THREAD

**Issue by adank92** [duneanalytics/spellbook#6160]
### Description
The `tokens_solana.transfers` table is not showing all transfers within a transaction. It was working fine 2 days ago.

### Current behavior
The following query shows a single transfer per transaction: https://dune.com/queries/3823383

```
SELECT * FROM tokens_solana.transfers WHERE tx_id IN ('c9itnmKSYGfiB5x8vNbS3WtNRWdMhfsLZQsRuJ9JhBwZE5X12oVdyTnGGFesEmC5oNBSVtSzfvFFUDdp3rSjqeh', '5yDxF8yiMFdHFM3gcrSzUUckjJSeQ57Bhp1GS1gbYkMFVFLoDeJvdYBxfV9jr4USt2dTurg8Cj1tVCY6PRHVE2K2') AND block_time >= (CURRENT_DATE - INTERVAL '10' day)
```

### Expected behavior
The transactions have multiple transfers each, so the query should show all of them:

https://solscan.io/tx/c9itnmKSYGfiB5x8vNbS3WtNRWdMhfsLZQsRuJ9JhBwZE5X12oVdyTnGGFesEmC5oNBSVtSzfvFFUDdp3rSjqeh
https://solscan.io/tx/5yDxF8yiMFdHFM3gcrSzUUckjJSeQ57Bhp1GS1gbYkMFVFLoDeJvdYBxfV9jr4USt2dTurg8Cj1tVCY6PRHVE2K2

### Impacted model(s)
`tokens_solana.transfers`

**Comment by jeff-dude** [comment]
@andrewhong5297 heads up on this new bug
@aalan3 in case we need to rebuild

**Comment by andrewhong5297** [comment]
good catch, we've found the root cause of the issue

**Comment by aalan3** [comment]
@adank92 thanks for creating the issue. We updated this https://github.com/duneanalytics/spellbook/blob/main/models/tokens/solana/tokens_solana_transfers.sql#L79-L80 to be INNER joins but it should be LEFT joins. We will fix this and I'll refresh the model tomorrow.

**Comment by adank92** [comment]
@jeff-dude @andrewhong5297 @aalan3 thank you all for resolving this so quickly!

**Comment by aalan3** [comment]
This is fixed since yesterday

**Comment by adank92** [comment]
I confirm it is, thank you!
