### ISSUE TITLE
[Feature] Adding new dexes for blast chain

### ISSUE THREAD

**Issue by Hosuke** [duneanalytics/spellbook#6271]
### Description
This proposal seeks to integrate several key dexes from the expanding Blast Chain into the Dune Spellbook to enhance data analytics and support comprehensive decision-making across the ecosystem.

### Proposed DEXes
Here are the dexes I propose to integrate:
- [x] thruster #6193 
- [ ] ambient
- [x] blasterswap #6294 
- [ ] bladeswap #6274 
- [x] fenix #6307 
- [ ] mangrove

**Comment by jeff-dude** [comment]
> ambient and mangrove are not uniswap compatible.
> 
> ambient documentation (they do not emit `swap` event): https://docs.ambient.finance/developers/deployed-contracts
> 
> mangrove documentation: https://docs.mangrove.exchange/developers/addresses/contract-addresses

thank you, i've forwarded the word on these to the team.

**Comment by jeff-dude** [comment]
considering this complete. as noted above, ambient and mangrove not added. bladeswap also not added, as it has complexities on how to pull the data rather than a simple fork.
