### ISSUE TITLE
Track Aave V3 Ethereum Lido market in `lending` namespace

### ISSUE THREAD

**Issue by defispartan** [duneanalytics/spellbook#6491]
### Description

The Aave DAO recently deployed a new Aave V3 market to Ethereum mainnet for Lido Protocol assets.

The contracts have already been decoded here: https://dune.com/queries?category=decoded_project&namespace=aave_v3&contract=LidoPool&blockchains=ethereum

We would like this market to be tracked in the `lending` spellbook namespace.

### Impacted model(s)

```
lending.supply
lending.borrow
lending.flashloan
```

**Comment by tomfutago** [comment]
Added: #6493 

p.s. it's not a bug, is it?

**Comment by defispartan** [comment]
@tomfutago tysm!

Nope, not a bug, that was the only option to open an issue
