### ISSUE TITLE
[BUG] mantle included in l2_revenues but not in gas_fees

### ISSUE THREAD

**Issue by andrewhong5297** [duneanalytics/spellbook#6494]
Was examining a dashboard (https://dune.com/queries/3913507/6578648) and noticed mantle revenues were zero, dug deeper and found that mantle is included in [l2_revenue](https://github.com/duneanalytics/spellbook/blob/main/dbt_subprojects/hourly_spellbook/models/_sector/rollup_economics/ethereum/l2_revenue.sql) table but not in the underlying [gas_fees](https://github.com/duneanalytics/spellbook/blob/main/dbt_subprojects/daily_spellbook/models/_sector/gas/fees/gas_fees.sql) table. We may want to have some way of checking blockchain inclusion across the lineages of these spells in the future.

**Comment by jeff-dude** [comment]
good to know, thanks for raising.

@0xRobin let's discuss in our RW meeting tomorrow, as we want to focus on enhancing `gas.fees` in general

**Comment by andrewhong5297** [comment]
I'm working on a quick PR for this now
