### ISSUE TITLE
[BUG] No price for ALPH

### ISSUE THREAD

**Issue by sven-hash** [duneanalytics/spellbook#6501]
### Description
We have added ALPH in `dbt_subprojects/tokens/models/prices/ethereum/prices_ethereum_tokens.sql` to get ALPH price trough coinpaprika API

PR: https://github.com/duneanalytics/spellbook/pull/6484

### Current behavior
`price.usd` is empty
![image](https://github.com/user-attachments/assets/cf3bf206-3d0a-4448-880c-3ca6ca4a2bf1)

### Expected behavior

Show ALPH price as a list

### Impacted model(s)

```
prices_ethereum_tokens.sql
```

**Comment by jeff-dude** [comment]
thanks for raising the issue. the price feed can take multiple days to refresh sometimes. plz do check again tomorrow and follow up with me here 🙏

**Comment by jeff-dude** [comment]
okay, thank you for following up. i have raised this to an internal team to see what could be happening. thanks for the patience.

**Comment by sven-hash** [comment]
Thanks a lot for your help
