### ISSUE TITLE
[Request] Add block_slot column to solana_utils.latest_balances

### ISSUE THREAD

**Issue by enriquerodbe** [duneanalytics/spellbook#6527]
Hi,
I would like to query Solana balances at a given block slot, but that column isn't available in `solana_utils.latest_balances` nor `solana_utils.daily_balances`.
I looked at the model [here](https://github.com/duneanalytics/spellbook/blob/main/dbt_subprojects/solana/models/solana_utils/solana_utils_daily_balances.sql#L29) and it seems it would be possible to "just add it" because it's available from the `updated_balances` view. But I'm new to Dune so I wanted to ask.

**Comment by dianag-md** [comment]
@jeff-dude, could you please let us know the timeframe for getting a yes or no? And if it's a yes, what would it take? We have tight deadlines on our end and were not aware that Dune lacks this capability for Solana. It's important to set the right internal expectations and be able to make some decisions. Thank you so much!

**Comment by andrewhong5297** [comment]
yup this seems fine to add

**Comment by jeff-dude** [comment]
> @jeff-dude, could you please let us know the timeframe for getting a yes or no? And if it's a yes, what would it take? We have tight deadlines on our end and were not aware that Dune lacks this capability for Solana. It's important to set the right internal expectations and be able to make some decisions. Thank you so much!

it's not that dune lacks this capability for solana, it's simply that the column isn't mapped through to the final curated table as @enriquerodbe mentioned. looks like we're good to add, so are you comfortable opening a PR to add that column to both models? if so, you can tag here and we can get into prod for you asap.

**Comment by enriquerodbe** [comment]
@jeff-dude @andrewhong5297 I sent PR #6539 . Please review.
There's a failing action regarding some CLA signature. Not sure what to do about that! Thanks.
