### ISSUE TITLE
[BUG] evms.transactions has rows with negative gas used

### ISSUE THREAD

**Issue by MSilb7** [duneanalytics/spellbook#6565]
### Description

evms.transactions has rows with negative gas used, which causes queries using it to fail

See: https://dune.com/queries/3992009

**Comment by jeff-dude** [comment]
looks like this is due to mode chain using a different data type in the raw data for that field.
```
SELECT
     gas_used,
     typeof(gas_used)
FROM
  "delta_prod"."mode"."transactions"
limit
  10
```
returns `uint256`

```
SELECT
     gas_used,
     typeof(gas_used)
FROM
  "delta_prod"."ethereum"."transactions"
limit
  10
```
returns `bigint`

**Comment by jeff-dude** [comment]
@0xBoxer @agaperste 
are we enforcing data types on hosted blockchains? why does `mode` differ than fully managed chains?

**Comment by agaperste** [comment]
Thanks for raising @jeff-dude, I will discuss with blockchain team internally

**Comment by jeff-dude** [comment]
thank you for raising @MSilb7 
i can confirm there was a bug in data types from the hosted blockchains being added. the blockchain team has fix and i've refreshed the view, now the query runs.
