### ISSUE TITLE
Missing Chains in Table Aggregation

### ISSUE THREAD

**Issue by bh2smith** [duneanalytics/spellbook#6569]
https://github.com/duneanalytics/spellbook/blob/ea76a11fcc7800da0b430c10ac73a5b1579427ab/dbt_subprojects/daily_spellbook/models/_sector/gas/fees/gas_fees.sql#L11-L21

I can see that several other gas tables are available here, have they been intentionally excluded because the native asset differs from ETH?

**Comment by jeff-dude** [comment]
closing due to comment in attached PR. we are working on full `gas.fees` lineage.
