### ISSUE TITLE
[BUG] curvefi.trades doesnt have data due to project name changed

### ISSUE THREAD

**Issue by 0xroll** [duneanalytics/spellbook#6586]
### Description

```
select * FROM curvefi.trades
```

no output here due to the [spell](https://github.com/duneanalytics/spellbook/blob/main/dbt_subprojects/dex/models/_projects/curvefi/curvefi_trades.sql#L38) filtering `curvefi` instead of `curve`

### Possible solution

changing from `curvefi` to `curve` will work

```
SELECT * FROM dex.trades
WHERE project = 'curve'
limit 10
```

**Comment by jeff-dude** [comment]
thank you for raising.

the value `curvefi` is used across all file names, directories, etc -- then indeed has `curve` written to `dex.trades`. i wonder if we should actually update that to be `curvefi` instead, then the view would be fine.

if i go to curve app, they have a link at the bottom directly to dune dashboard:
https://dune.com/mrblock_buidl/Curve.fi

they use `curvefi` naming standard 🤔

**Comment by 0xBoxer** [comment]
I think `curve` is the most commonly used name for the dex though, think changing to `curve.trades` should be fine.

This will also be a lot less complex than changing any row values of dex.trades, I doubt many people use that table today.

**Comment by jeff-dude** [comment]
i also noticed `curve` is used in labels

i will update spellbook file names and such and fix the view
