### ISSUE TITLE
@jeff-dude This is my answer to your question on Discord

### ISSUE THREAD

**Issue by AIDataMaster** [duneanalytics/spellbook#6594]
@jeff-dude This is my answer to your question on Discord

I decided to change the logic of working with assets on GMX protocol
This protocol has event "MarketCreated". It generates all assets that are traded on dex.
There are some real assets like SOL and some synthetic assets like DOGE.
So, it means that tokens.erc20 does not have synthetic tokens - yes, I did investigation on Dune first! 

I did 2 iterations:
1st iteration: I added synthetic tokens to tokens_<chain>.erc20 but I did it manually.
It means that if I don't insert a new token manually then the subsequent models can crash on the next build. 
Why? 
We have erc20 -> MarketCreated -> EventModel
If erc20 is not updated then MarketCreated will have NULL in some of rows because I use LEFT JOIN for 2 tables: MarketCreated and ERC20Tokens
If MarketCreated is crashed or has NULL values in decimals it means that EventModel will not apply POWER function correctly.
POWER function return NULL for POWER(10,NULL). It means that all rows for new market will not be updated correctly.

My decision: I reverted all updates for synthetic tokens in subproject "tokens"

2nd iteration:
So, we decided to create a separate model of all assets on GMX based on API endpoint to fetch all markets available on exchange. 

You can see that model in path: ".../daily_spellbook/models/_projects/gmx/tokens/<chain>/<model>.sql

_Originally posted by @AIDataMaster in https://github.com/duneanalytics/spellbook/issues/6579#issuecomment-2305430007_

**Comment by jeff-dude** [comment]
thank you, we can continue conversation in the PR itself
