### ISSUE TITLE
[BUG] Blast included in l2_revenues but not in gas_fees

### ISSUE THREAD

**Issue by abdelhaqs** [duneanalytics/spellbook#6596]
I was updating my dashboard (https://dune.com/queries/3913576/6578765) and noticed Blast revenues were zero, I found that Blast is included in [l2_revenue](https://github.com/duneanalytics/spellbook/blob/main/dbt_subprojects/hourly_spellbook/models/_sector/rollup_economics/ethereum/l2_revenue.sql) table but not in the underlying [gas_fees](https://github.com/duneanalytics/spellbook/blob/main/dbt_subprojects/daily_spellbook/models/_sector/gas/fees/gas_fees.sql) table.

**Comment by jeff-dude** [comment]
closing this similar to the PR. we are aware of `gas.fees` gaps and working to fix all EVM chains
