### ISSUE TITLE
The first link in the folder docs/ci_test/ci_test_overview.md is inactive

### ISSUE THREAD

**Issue by Olexandr88** [duneanalytics/spellbook#6644]
### Impacted model(s)

```
namespace.model
```

**Comment by Olexandr88** [comment]
Namely /.github/workflows/dbt_slim_ci.yml

Any time a PR is opened in Spellbook, there are a few GH workflows which automatically run on each commit. The `dbt slim ci` workflow kicks off the continuous integration (CI) tests, which are required to pass in order to prepare for final merge into the main branch. The code which runs the CI workflow can be found [here](/.github/workflows/dbt_slim_ci.yml), but in general, the steps included are:

**Comment by jeff-dude** [comment]
thank you for raising. i have attached PR to fix. this will close when merged.
