### ISSUE TITLE
[BUG] dex.trades table missing token symbols partially in some swaps while it's present in other swaps

### ISSUE THREAD

**Issue by sui414** [duneanalytics/spellbook#6650]
### Description

Some tokens symbols are missing in some entries but not missing for other swaps - it looks like a issue with some specific pools: 

see the example here checking RENZO token - https://dune.com/queries/4032804

### Expected behavior

If the token symbol is available by the time of insertion for any swap pair, that means the token meta info is available, should double check if some dex decoding is using a outdated token table in joining.

### Impacted model(s)

```
namespace.model
```

dex.trades

**Comment by jeff-dude** [comment]
@sui414 thank you for raising. this appears to be only 1inch trades which contain this tokens symbol. 1inch team maintains their own pipeline that feeds into `dex.trades`, and it appears there is slightly different logic for applying symbol within those models vs. the rest of the pipeline.

1inch code:
- applies a `coalesce()` on symbol for left joins to both `prices.usd` and `tokens.erc20`, to grab from either when available

rest of dex trades code:
- only pulls from `tokens.erc20` metadata

we had recently undergone and effort to automate erc20 token metadata via a third party API, but we are still missing some tokens in that source. we have left open the option to manually add tokens to compliment the automated source until resolved. there will also be changes to how prices pipelines are run in the near future, which may make the coalesce example above to be irrelevant.

my suggestion for now is to add the token manually here:
https://github.com/duneanalytics/spellbook/blob/main/dbt_subprojects/tokens/models/tokens/ethereum/tokens_ethereum_erc20.sql

until we have the opportunity to figure out the gaps in the automated source for token metadata

**Comment by jeff-dude** [comment]
quick query proof:
```
select
  'erc20_metadata',
  symbol
from
  tokens.erc20
where
  blockchain = 'ethereum'
  and contract_address = 0x3b50805453023a91a8bf641e279401a0b23fa6f9
union all
select distinct
  'prices_metadata',
  symbol
from
  prices.usd
where
  blockchain = 'ethereum'
  and contract_address = 0x3b50805453023a91a8bf641e279401a0b23fa6f9
```

**Comment by sui414** [comment]
thanks for investigating! 
is it only 1inch insertion? i checked a few of those tx hash example (in my test query above)

and it seems to also be a issue with some 

- Odos trades sourcing uniswap liquidity (no 1inch router involved): https://etherscan.io/tx/0xfff98bbfa81af5dcd1cac5011c8340a9b2c9426608b9341f73d488af6cd574c8

- Kyber swap: https://etherscan.io/tx/0xface83ee06ebb0f8e6c4d5698e2009b85e9681148c4c4fcb385af3362be7c753


Also, note that im checking against liquidity pool in `dex.trades` (not `dex_aggregator.trades`)- so if it's showing that some uniswap pools is missing the token symbol, it means it comes from the uniswap decoding as i understand.


I think the issue you pointed out can explain why the `project = '1inch-LOP'` was missing symbol but there are other `0x-API` and `uniswap` ones are missing it 🤔 (cc @RantumBits @bakabhai993 for 0x trades)

**Comment by sui414** [comment]
sounds good and thanks for investigating!
These LRT tokens are trading decent amount of volume, but i guess it's not too bad given it's not affecting the volume number.

**Comment by jeff-dude** [comment]
i will close this as resolved for now, but feel free to add tokens to those chain specific static files as needed 🤝
