### ISSUE TITLE
[BUG] nft.trades wrong number_of_items

### ISSUE THREAD

**Issue by palevoo** [duneanalytics/spellbook#6673]
### Description

Seems for project "element" in table nft.trades it sometimes returns  wrong number of `number_of_items` , seems to be some default value of 1 (maybe something to do with ERC1155 being treated differently and ironing value)

 https://basescan.org/tx/0x6c860c7a5354a80856d660bd5d3787beeef71b36d42629641b5c81cf0e7effe7, but query returns 1, here is example query https://dune.com/queries/4038379 to find some of the wrong records.

### Current behavior

Here is an example tx with 125 traded https://basescan.org/tx/0x6c860c7a5354a80856d660bd5d3787beeef71b36d42629641b5c81cf0e7effe7

but nft.trades returns 1, here is an example query https://dune.com/queries/4038379 to find some of the wrong records.

### Expected behavior

Should show correct `number_of_items`

### Impacted model(s)

```
nft.trades
```

### Possible solution

Not sure, but maybe issue is with nft_amount in elements trades here https://github.com/duneanalytics/spellbook/blob/c27322855b55d5dd04067083075579b2bb211b5d/dbt_subprojects/nft/macros/platforms/element_v1_base_trades.sql#L91, not sure how thats how the mapping works between element.nft_amount and nft.trades.number_of_items

**Comment by 0xRobin** [comment]
@palevoo you're absolutely right, thanks for filing this bug!
PR with a simple fix is up, I'll verify your example transactions
