### ISSUE TITLE
[BUG] no data in dex.trades for sushiswap 2 on arbitrum 

### ISSUE THREAD

**Issue by 0xroll** [duneanalytics/spellbook#6687]
### Description

in the dex.trades, swaps that happened on sushiswap version 2 are not showing up .

this is due to the sushi_v2_arbitrum.Pool_evt_Swap table that is being pointed to in the spell is empty

https://github.com/duneanalytics/spellbook/blob/main/dbt_subprojects/dex/models/trades/arbitrum/platforms/sushiswap_v2_arbitrum_base_trades.sql#L18

### Current behavior
no swap data because source table is null

### Expected behavior
data should be populated if source table has the decoded transactions

### Impacted model(s)

https://github.com/duneanalytics/spellbook/blob/main/dbt_subprojects/dex/models/trades/arbitrum/platforms/sushiswap_v2_arbitrum_base_trades.sql#L18

### Possible solution

there is another table that decodes the swap transactions for sushiswap

```
select * FROM sushiswap_v3_pool_arbitrum.UniswapV3Pool_evt_Swap
limit 100
```

changing the source tables to this table above in the base trades model should work

**Comment by jeff-dude** [comment]
@0xroll @Hosuke 
i got some more info around the decoded tables for sushiswap here. i'm not sure if you think we should take more action to fix source decoded tables or not, but will share info here.

> Somehow a contract was inserted into the pipelines with multiple instances flag enabled (while most likely it shouldn't). The address is this one: 0xaf8dc790c4e1859fe0101c30667280c5ee23a661
> 
> The ABIs between v2 and v3 are the same. Thats the reason you notice it as just a naming change.
> 
> However the sushiswap_v3_pool.UniswapV3Pool  contract covers 14320 addresses (that's because a contract was submitted with factory settings enabled). You can check that by querying:
> `SELECT * FROM arbitrum.contracts WHERE name = 'UniswapV3Pool' AND namespace = 'sushiswap_v3_pool'`
> 
> While it decodes the transactions you test about, it might contain transactions you don't want to be decoded as a v3.
> 
> Why v2 doesn't have any data ?
> That's something I cannot explain. The only way I believe this can happen is  an engineer manually deleting the data.
> I am not sure what we need to do. Do we want to have the v2 at address 0x4ff2cd6a3575ecf5057cb5ff320e9f6613e693d8 resurrected ?
> 
> What I would do ?
> - I would change the submission of contract 0xaf8dc790c4e1859fe0101c30667280c5ee23a661 and remove the factory settings. First I would delete the contract and the data. Then re-submit without the factory settings. This means you will not have data for a while.
> - Re-submit the contract 0x4ff2cd6a3575ecf5057cb5ff320e9f6613e693d8. This way we get data back for v2 contract.

**Comment by Hosuke** [comment]
I think we can keep the current decoded tables.
(Maybe we can have a source monitoring test? Monitoring count(*) from evt_swap dropping or becoming `0`)
