### ISSUE TITLE
erc20.tokens is missing SOS token

### ISSUE THREAD

**Issue by ian-whitestone** [duneanalytics/spellbook#679]
https://etherscan.io/token/0x3b484b82567a09e2588a13d54d032153f0c0aee0

Similarly, `ethereum.contracts` is missing this address as well. It's both the SOS token and the OpenDAO contract.

**Comment by masquot** [comment]
Thank you @ian-whitestone. SOS arived with a bang. 

Anyone can contribute to Dune via a simple PR.
- A new token (for Ethereum) can be added here: https://github.com/duneanalytics/abstractions/blob/master/ethereum/erc20/tokens.sql
- Info on how to submit contracts is here: https://docs.dune.xyz/data-tables/data-tables/decoded-data

Dune's Discord is the best place if you need help: https://discord.gg/ErrzwBz

**Comment by aditzeus** [comment]
I also lost the ENS token. how fix my wallet 0x42Cf60bB2f6B3220372dFc4FD27A2Df8F1c725F0
aditzeustube.eth

**Comment by aditzeus** [comment]
whatvis this


Pada tanggal Sel, 27 Sep 2022 8.26 PM, soispoke ***@***.***>
menulis:
