### ISSUE TITLE
Multiple Entries per Symbol in `prices.usd_latest`

### ISSUE THREAD

**Issue by zakraicik** [duneanalytics/spellbook#6818]
**Summary**
`prices.usd_latest` is expected to have only one entry per symbol (the latest price). However, some symbols have multiple entries, often due to discrepancies in the symbol's decimals. This can cause issues when performing joins or calculations.

**Example**
```
select * 
from prices.usd_latest 
where blockchain = 'ethereum' AND symbol = 'PEIPEI'
```

**Implications**

- Increased row count in joins: Unintentionally, the number of rows can increase if these discrepancies are not accounted for in queries.
- Incorrect conversions: The inconsistency in decimals can result in incorrect value conversions, especially in interactions with protocols like Uniswap V3 during liquidity calculations.

**Comment by jeff-dude** [comment]
hi @zakraicik -- we should not filter / join on symbol column. the uniqueness of prices is always going to be `blockchain, contract_address`.

any token can use any symbol they want. there isn't much we can do to get around that. i would suggest changing your approach and use symbol solely for metadata

**Comment by zakraicik** [comment]
Thanks @jeff-dude !!
