### ISSUE TITLE
[BUG] missing dex.trades data

### ISSUE THREAD

**Issue by palevoo** [duneanalytics/spellbook#6867]
### Description

select * from dex.trades where tx_from = 0x1c3e051ab396683485e316d6886b7d5c22c147fe

doesn't have this tx https://etherscan.io/tx/0x554fe5beb1ca2dfa60c698e6204c748756170857aaab6ca9582d2465c7f18836

### Current behavior

Returns impartial trades

### Impacted model(s)

```
dex.trades 
```

### Possible solution

No idea tbh, sorry.

**Comment by 0xdatawolf001** [comment]
Banana gun is not a technically a DEX. It merely routes the order through a Uniswap pool. Also, the transaction that palevoo is talking about is present in Dex trades but its considered a Uniswap transaction. 

Filtering on tx_to = '0x3328f7f4a1d1c57c35df56bbf0c9dcafca309c49' would give you trades coming from the banana gun router. Not sure if there is a need for addition or changes to dex.trades.

**Comment by jeff-dude** [comment]
thank you v much for your kind contribution here!

i will consider this closed, as a new way to query `dex.trades` to find trades routed through banana gun
