### ISSUE TITLE
dex.trades 1inch-LOP on ETH token SOLD and BOUGHT should be reverse

### ISSUE THREAD

**Issue by 0xSerPablo** [duneanalytics/spellbook#6915]
### Description

DEX.TRADES for project 1inch-LOP on ETH token SOLD and BOUGHT are incorrect and should be reverse.

### Current behavior
ETH token SOLD and BOUGHT are incorrect and should be reverse.

### Expected behavior

Current:
![image](https://github.com/user-attachments/assets/561a670a-3fa2-499f-a2fe-1be1c0650bdc)

Expected:
![image](https://github.com/user-attachments/assets/692e10e6-3ba3-4f90-851f-a67563b5c7e4)

TXL https://etherscan.io/tx/0x488f2bd6a6cf9f9f9bf0b9d550e3b3a00d31af58d873d2923830c3c0ba2731ce

### Impacted model(s)
dex.trades

```

### Possible solution
<!--If you can think of a possible way to address this issue, please feel free to detail it here. 
Any additional information such as smart contract internals will be very helpful as well.-->

**Comment by 0xSerPablo** [comment]
SQL
SQL:

select * from dex.trades
where 
project = '1inch-LOP' and tx_hash = 0x488f2bd6a6cf9f9f9bf0b9d550e3b3a00d31af58d873d2923830c3c0ba2731ce

**Comment by jeff-dude** [comment]
@max-morrow @grkhr 
can you provide input here?
