### ISSUE TITLE
Get # of wallets holding above 100K USDC across EVMs

### ISSUE THREAD

**Issue by DaKingLawson** [duneanalytics/spellbook#6946]
Hi, 
I'm new to dune and for context, am not very technical. I'm looking to create a query that gets the # of wallets holding over $100k of the following ERC20 tokens across the most popular EVM chains. 
- USDC
- USDT 
- ETH
- wBTC
- SHIB

Any help would be greatly appreciated.

**Comment by jeff-dude** [comment]
gm @DaKingLawson 
typically issues raised in this repo are related to how to translate existing queries into spells and/or fix bugs in existing spells. have you tried asking for support on this request in the dune discord for query questions?

**Comment by DaKingLawson** [comment]
My apologies. I was watching this [video](https://youtu.be/9Dx4HNGcSCo?si=JlxNgk7sj9bdrAJ5) where they told me this was the place to come if you’d like to request help with creating a new query. Can you point me in the right direction?

**Comment by jeff-dude** [comment]
have you tried this channel?
https://discord.com/channels/757637422384283659/757641002138730588

**Comment by jeff-dude** [comment]
closing with intention of query questions being answered in discord
