### ISSUE TITLE
[BUG] tokens_solana.transfers returns no data when directed at Token2022 programs

### ISSUE THREAD

**Issue by rsellers** [duneanalytics/spellbook#7093]
### Description
I maintain a few dune tables which query over transfers pertaining to a certain project with token_mint_address = 'xNETbUB7cRb3AAu2pNG2pUwQcJ2BHcktfvSB8x1Pq6L'. Starting 10/31 or 11/01, the tables broke with my queries retuning no data. I had no issues before, and I've isolated the issue to stem from the tokens_solana.transfers query when filtering by certain contract addresses. 

My contract address program is a little unique in that its a token2022 version. That seems to be the only thing which is special about it. So either the root cause is related to token2022 or something totally different. 

### Current behavior
A query from this table returns blank when token_mint_address points towards a token 2022 mint address. 

Example query retuning blank with token 2022 program: 
SELECT *
    FROM
        tokens_solana.transfers
    WHERE
        token_mint_address = 'xNETbUB7cRb3AAu2pNG2pUwQcJ2BHcktfvSB8x1Pq6L' -- XNET Token 2022 program
    LIMIT 2

### Expected behavior
I need the tokens_solana.transfers to function correctly and list all the transfer data so I can continue to operate my tables. 

Example *successful* query retuning expected information for a regular token program (dogwifhat for example): 
SELECT *
    FROM
        tokens_solana.transfers
    WHERE
        token_mint_address = 'EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm' -- dogwifhat regular token program
    LIMIT 2

### Impacted model(s)
I'm not sure what to put for models. 

### Possible solution
I don't have any suggestions right now, unfortunately.

**Comment by jeff-dude** [comment]
thank you for raising. as mentioned by boxer above, i will link PR with fix
