### ISSUE TITLE
ERC20_evt_Transfer.value could be inaccurate

### ISSUE THREAD

**Issue by zjiekai** [duneanalytics/spellbook#875]
In [this `Transfer` event query](https://dune.xyz/queries/468707), the `value` is `1000000000000000000`.  But in [etherscan](https://etherscan.io/tx/0xaabbcee047ca32ada83d22d199106352de804264cba390aa7f2125da3121d00c#eventlog), it's `999999999999999999`.

**Comment by soispoke** [comment]
Please use our new v2 engine, the issue is fixed there: https://dune.com/queries/1320880
