### ISSUE TITLE
how to find the all tables

### ISSUE THREAD

**Issue by machen382847508** [duneanalytics/spellbook#876]
How to find the all tables in 'ethereum' ,which now do not have all table ,for example uniswap_v2??

**Comment by soispoke** [comment]
You can find the tables by looking at the data explorer, see screenshot here:
<img width="403" alt="Capture d’écran 2022-09-27 à 13 32 55" src="https://user-images.githubusercontent.com/66172107/192527347-88761488-0558-4b45-8deb-dc82bb26a0e5.png">
