### ISSUE TITLE
Some thoughts on duplicated OpenSea rows in nft.trades

### ISSUE THREAD

**Issue by onesuper** [duneanalytics/spellbook#898]
Hi, @masquot 

According to my investigation, multiple swaps within one transaction may bring duplicated rows in nft.trades.

Take this tx([0xbbed44a3f6ba1bdfb...](https://etherscan.io/tx/0xbbed44a3f6ba1bdfb39224e8b8c53d2ea3e7448ba2221137c80012603e7b3540)) as an example:  

<img width="815" alt="image" src="https://user-images.githubusercontent.com/977633/158108604-afaabb77-1171-46df-a4f4-1c3139cfa42b.png">

It conducts 52 erc721 exchanges as a proxy for OpeaSean.

Using tx_hash as join key, the [left join SQL](https://github.com/duneanalytics/abstractions/blob/30ae3632a763e7e7e2fd4d2cd24097d51bb6228a/ethereum/nft/trades/insert_opensea.sql#L170) may produce a [Cartesian product](https://docs.oracle.com/cd/E29587_01/PlatformServices.60x/ps_forge/src/cfrg_joins_adv_mult_recs.html), thus generating duplicated rows. Theoretically, there will be 2704(52x52) rows about this tx in nft.trades.

I notice nft.trades table has some unique index constraints, but there are still 1494 rows being inserted according to my Dune query: https://dune.xyz/queries/495980.

### An overview of this problem

I [aggregate the OpenSea trades](https://dune.xyz/queries/496024) of 2022-01-01. 

863 transactions(with multiple erc721 tansfers inside) produce 29741 records (the expected number is 4329).

<img width="834" alt="image" src="https://user-images.githubusercontent.com/977633/158109952-2f35eaf2-09e9-4dfd-a956-c866dab86390.png">

The vast majority of cases are caused by GenieSwap [0x0a267cf51ef038fc00e71801f5a524aec06e4f07](https://etherscan.io/address/0x0a267cf51ef038fc00e71801f5a524aec06e4f07) and only few other contracts.

I also wrote a more detailed [survey](https://app.datawaves.xyz/notebook/30c35f65-fec2-4d33-ac64-65d41cd54378) to analyze the problem and be able to reproduce the problem on my dataset.

Let me know what you think!

**Comment by themez** [comment]
I believe this issue was fixed in `nft.trades_v2_beta` table: https://dune.com/queries/870181
However, there're other issues in v2 table, maybe that's the reason the SQL which generates this table is not published yet.

**Comment by soispoke** [comment]
Closing the issue as we're now maintaining nft.trades on the V2 engine
